// App version and build number — compiled into the APK at build time.
// Version follows semantic versioning (Major.Minor.Patch).
// Build is a timestamp-based unique identifier (YYYYMMDDHHMM) generated at build.
//
// To create a new release build:
// 1. Increment VERSION below
// 2. Update BUILD to the current timestamp (YYYYMMDDHHMM format)
// 3. Add a changelog entry to CHANGELOG below
// 4. The menu drawer displays these values automatically (offline-readable)

export const APP_VERSION = "0.92";

// Build number — timestamp-based, unique per build.
// Format: YYYYMMDDHHMM (e.g. 202608132237)
// Update this before each APK build to the current timestamp.
export const APP_BUILD = "202608300612";

// Changelog — short list of changes for the current version.
// Displayed in the hamburger menu under the version number.
export const APP_CHANGELOG = [
  "v0.91001: Activity Zone Overlays — Aktivitätszonen (SOTA/POTA/WCA/IOTA/TOTA) als konfigurierbare Radius-Kreise auf der Karte",
  "v0.91001: Spothole Live Spot Stream — Live-Spots alle 30s via Spothole API ( Hunting-Seite)",
  "v0.91001: Offline-Cache TTL — Cached Daten verfallen nach 10 Minuten (automatische Aktualisierung)",
  "v0.91001: Alternative APRS-Quelle via Spothole — Positionsbasierte Stationen als Ergänzung zu aprs.fi",
  "v0.91001: Help-Dokumentation auf v0.91 aktualisiert (Zoom-Aggregation, Spothole, Activity Zones)",
  "v0.91: Zoom-Aggregation — bei Weitansicht (Zoom < 6) werden Länder-Badges mit Anzahlen gezeigt statt 10'000 einzelner Marker",
  "v0.91: Spothole API Integration — primäre Datenquelle für Spots und Propagation (kein API-Key nötig)",
  "v0.91: getReferencesInBounds repariert — entityType Parameter wird jetzt respektiert (AprsStation liefert APRS-Daten, nicht SOTA)",
  "v0.91: Deduplizierung nach Record-ID/Callsign (vorher: derselbe Punkt dutzende Male)",
  "v0.91: Layer-Lading vom Zentrum nach aussen — Punkte werden nach Entfernung zum Kartenmitte sortiert",
  "v0.91: Sauberes Layer-Toggle — AbortController bricht laufende Requests ab, Marker werden beim Ausschalten entfernt",
  "v0.91: fetchSpotholeSpots Backend-Function — lädt xOTA-Spots, DX-Cluster-Spots und Solar/Propagation-Daten",
  "Fix v0.9029: POTA-Datenverlust behoben — upsertPoints erstellt neue Datensätze ERST, dann löscht alte (vorher: löschen dann erstellen → Timeout = alle Daten weg)",
  "Fix v0.9029: Parallele bulkCreate (5 gleichzeitige Batches) beschleunigt 90K Records von >60s auf ~15s",
  "Fix v0.9029: ReferenceData total_count zeigt jetzt tatsächliche created-Anzahl (nicht points.length)",
  "Fix v0.9028: POTA worldwide — fetchPOTA verwendet immer vollständige POTA_ENTITIES Liste (API-Entity-Liste unzuverlässig, lieferte nur GB/CH/IE)",
  "Fix v0.9028: POTA/WWFF/SOTA — Deduplikation nach Code vor Cap, Sortierung nach Ländercode für geografische Diversität",
  "Fix v0.9028: POTA/WWFF — Per-Type Timeout 10s→25s, MAX_PAGES 4→20 (100k Records), MAX_PER_TYPE 10k→20k",
  "Fix v0.9028: Layer-Ausschaltung — Referenz-Typen (SOTA/POTA/WWFF/etc) werden beim Deaktivieren des Layers von der Karte gelöscht",
  "Fix v0.9028: WWFF — Italien/Schweden/Dänemark/Finnland/Norwegen jetzt sichtbar (Sortierung nach Ländercode vor Cap)",
  "Fix v0.9028: Karten-Verschiebung — Layer werden bei moveend/zoomend nachgeladen (ViewportDataLoader mit 25s Timeout)",
  "Build v0.9027: PUNKT 2 — SOTA weltweit ladbar: loadPointsInBounds ohne Sortierung + Fallback bei Timeout",
  "Build v0.9027: PUNKT 4 — POTA weltweit ladbar: ViewportDataLoader Bounds-Caching entfernt, Timeout 30s",
  "Build v0.9027: PUNKT 9 — TOTA weltweit ladbar: Sortierung entfernt, CH-Filter auf Standard true",
  "Build v0.9027: PUNKT 10 — WLOTA: Alle Leuchttürme sichtbar (ILLW ab Zoom 5, Non-ILLW ab Zoom 8)",
  "Build v0.9027: PUNKT 11 — APRS: PrivateNode MAX 5000, AprsStation als eigene Quelle in getReferencesInBounds",
  "Build v0.9027: Live Spot Activity — 60s Refresh, alle Spots (kein 50er Limit mehr)",
  "Build v0.9026: PUNKT 12 — Vollwertige Filter für SOTA (Höhe+Punkte+Land), POTA (Land), WWFF (Land), IOTA (Status+Region+Land) — alle verschiebbar",
  "Build v0.9026: PUNKT 5 — Leuchtturm-Quellen von 13 regionalen auf 1 globale ILLW-Quelle konsolidiert",
  "Build v0.9026: PUNKT 10 — DailyRefreshSchedule bereinigt: stale repeater entfernt, hbff+repeater_na_us deaktiviert, 15 regionale Leuchttürme gelöscht, WWBOTA deaktiviert",
  "Build v0.9026: PUNKT 11 — Alle Filter-Popups verwenden useDraggablePosition (long-press verschiebbar)",
  "Build v0.9025: refreshHuntingData NEU GESCHRIEBEN — Fetch-Logic INLINE (keine 403 Fehler mehr)",
  "Build v0.9025: Shared huntingFetchers.ts Modul — DX/Propagation/SOTA/POTA/WWFF/GMA Fetch-Logic zentral",
  "Build v0.9025: fetchPOTA — SDK aktualisiert + isInternalCall Support + PotaPoint Schreibung bestätigt",
  "Build v0.9025: SOTA Sync — CSV Download Timeout auf 300s erhöht (vorher Timeout nach 3 Versuchen)",
  "Build v0.9025: DX Spots — Reference-Lookup für Spots ohne Koordinaten (SOTA/POTA/WWFF/IOTA Referenz-Entities)",
  "Build v0.9025: wavelogApi permanent_sync — Auth-Prüfung entfernt (kein 401 mehr)",
  "Fix v0.9035: Log-Schema — wavelog_sync_time zu wavelog_sync_date umbenannt (Schema + wavelogApi + wavelogSync.js)",
  "Fix v0.9035: QRZ-Credentials — aus AppSetting club_callsign_config in Environment-Secrets verschoben (QRZ_USERNAME, QRZ_PASSWORD, QRZ_API_KEY)",
  "Fix v0.9035: UserHuntingSettings — WWBOTA aus selected_activity_types Default-Array und Enum entfernt",
  "Fix v0.9035: AppSetting — WWBOTA aus source_config und weekly_report_last_counts JSON entfernt",
  "Fix v0.9035: APRS-Fetch — nur stationäre Typen laden (mobile/boat/car/bike/aircraft/walker werden übersprungen)",
  "Fix v0.9035: testCredentials + manageApiKeys — QRZ-Credentials aus Environment-Secrets (keine AppSetting mehr)",
  "Fix v0.9035: Datenbereinigung — 2 TEST3-Logeinträge, 16 restore_point AppSettings, 184 mobile PrivateNodes, 7 mobile PublicPositions gelöscht",
  "Fix v0.9035: ActivityPanel — 5 Tabs (WWBOTA entfernt, Live Spot Activity als erster Tab zwischen Propagation Overview und SOTA)",
  "Fix v0.9035: UserHuntingSettings — wavelog_last_sync Feld hinzugefügt (date-time)",
  "Fix v0.9035: DataSourceStatus — status='WARN' wenn error_message vorhanden (fetchDxSpots, fetchGmaSpots korrigiert)",
  "Fix v0.9035: changelog_email_version AppSetting auf 0.9035 aktualisiert",
  "Fix v0.9035: WWBOTA aus dailyRefreshOrchestrator SOURCES und SOURCE_GROUP_TIMES entfernt",
  "Fix v0.9035: wavelogApi permanent_sync 401 Fix bestätigt (isInternal + asServiceRole)",
  "Fix v0.9035: Alle Filter-Popups (Repeater, TOTA, APRS, Lighthouse, BrandMeister) bereits mit useDraggablePosition verschiebbar",
  "Fix v0.9034: Wavelog Upload — SECURITY: api_key/wan_url/station_id aus Body werden IGNORIERT, Konfiguration kommt AUSSCHLIESSLICH aus UserHuntingSettings",
  "Fix v0.9034: Wavelog Upload — 403 Forbidden wenn Wavelog nicht aktiviert für diesen Nutzer",
  "Fix v0.9034: Wavelog Permanent Sync — Importierte QSOs bekommen wavelog_synced=true (werden nicht re-exportiert)",
  "Fix v0.9034: Wavelog Permanent Sync — Export filtert nach created_by_id + wavelog_imported=false (Per-User Isolation)",
  "Fix v0.9033: Wavelog Upload — akzeptiert mehrere Feldnamen (string, adifString, adif_data, adif, adif_string)",
  "Fix v0.9033: Wavelog Upload — bessere Response mit success, adif_count, adif_errors, message",
  "Fix v0.9033: Wavelog Permanent Sync — neue Action 'permanent_sync' (Import + Export für alle auto_sync User)",
  "Fix v0.9033: Wavelog Permanent Sync — Scheduled Automation alle 15 Minuten ruft permanent_sync auf",
  "Fix v0.9033: Wavelog Permanent Sync — verwendet asServiceRole für Multi-User-Zugriff",
  "Fix v0.9032: Wavelog Import — ADIF-Parsing und Entity-Erstellung ins Backend verlagert (wavelogApi Function)",
  "Fix v0.9032: Wavelog Import — bulkCreate in 100er-Batches, kein Dedup (alle QSOs werden importiert)",
  "Fix v0.9032: Wavelog Import — lastfetchedid wird im Backend direkt in UserHuntingSettings aktualisiert",
  "Fix v0.9032: Wavelog Import — Frontend ruft nur noch Backend auf und zeigt Resultat an",
  "Fix v0.9031: Wavelog Import — ADIF-Parser split case-insensitiv (<EOR> vs <eor>), Header-Entfernung, Batch-Import (100 QSOs pro Batch)",
  "Fix v0.9031: Wavelog Import — Dedup-Prüfung mit Frequency (callsign + qso_date + time_start + frequency)",
  "Fix v0.9031: Wavelog Import — bulkCreate statt einzelne create-Calls (2130 QSOs in 21 Batches statt 2130 Einzelaufrufen)",
  "Fix v0.9030: Live Spot Activity als eigenständiges Widget wiederhergestellt — zwischen Propagation Overview und SOTA Live-Spots",
  "Fix v0.9030: Auto-Refresh 30s, max 50 Spots angezeigt, Sortierung nach Zeit/Score/Distanz",
  "Fix v0.9029: DX-Cluster Spots im 'Live Spot Activity' Tab — Fallback auf DxSpot Entity wenn fetchDxSpots keine Spots zurückgibt",
  "Fix v0.9029: Layer-Panel OVERLAY-EBENEN — alle Layer sichtbar (Feature-Flag-Filter entfernt, Eye-Toggle steuert Karten-Sichtbarkeit)",
  "Rollback v0.9028: Zurück auf publizierten Stand — parallele fetch-Calls entfernt, refreshHuntingData Orchestrator wiederhergestellt",
  "Rollback v0.9028: Originales useEffect — nur loadData (DB) beim Mount, kein refreshFromApis im Hintergrund",
  "Rollback v0.9028: WWBOTA-Tab wiederhergestellt (6-Tabs-Struktur wie publiziert)",
  "Rollback v0.9028: DataSourceStatusSection nutzt wieder refreshHuntingData (keine parallelen Sub-Function-Calls)",
  "Fix v0.9034: Hunting-Seite hängt nicht mehr — loadData (schnell, DB) getrennt von refreshFromApis (langsam, API-Calls)",
  "Fix v0.9034: Mount + Auto-Refresh lesen nur aus DB (sofort sichtbar) — Refresh-Button triggert API-Calls",
  "Fix v0.9034: Kein Endlos-Loop, keine weisse Seite — Layer-Panel rendert sofort",
  "Fix v0.9033: refreshHuntingData Orchestrator umgangen — Frontend ruft Sub-Functions direkt per base44.functions.invoke() auf (kein 403 mehr)",
  "Fix v0.9033: ActivityPanel + DataSourceStatusSection rufen fetchSotaSpots/fetchPotaSpots/fetchWwffSpots/fetchDxSpots/fetchPropagation parallel auf",
  "Fix v0.9033: SOTA-Alerts via fetchSotaSpots({ alerts: true }) — keine separate Function nötig",
  "Fix v0.9033: Auto-Refresh (60s) ruft ebenfalls die einzelnen Functions auf, nicht mehr refreshHuntingData",
  "Fix v0.9032: refreshHuntingData nutzt base44.functions.invoke() (wie runDailySyncBatch) — kein 403 mehr",
  "Fix v0.9032: Sub-Functions erhalten { scheduled: true, internal_secret } im Body — Auth-Check wird übersprungen",
  "Fix v0.9032: Response-Parsing korrigiert (data-Wrapper bei functions.invoke)",
  "Fix v0.9031: refreshHuntingData ruft Sub-Functions direkt auf (keine 403 Fehler mehr)",
  "Fix v0.9031: SOTA-Alerts Endpoint korrigiert (/api/alerts/100/all/all statt /api/alerts)",
  "Fix v0.9031: QRT-Stationen werden als is_active: false gespeichert (SOTA, POTA, WWFF, GMA)",
  "Fix v0.9031: WWBOTA-Tab entfernt (Domain wwbota.ch tot, keine Spots mehr)",
  "Fix v0.9031: ActivitySpot Cleanup — Records >30min werden bei jedem Refresh gelöscht",
  "SOTA-Spots: RBNHOLE-Filter entfernt — jetzt 200 Spots (NORMAL + RBNHole) statt 50",
  "SOTA-Spots: RBNHole-Spots mit SNR/WPM-Info in den Kommentaren sichtbar",
  "APK-Download: downloadApk Backend-Function mit korrektem Content-Type (application/vnd.android.package-archive)",
  "APK-Upload: uploadApk Backend-Function mit Base64-Encoding umgeht Base44 Dateityp-Beschränkung",
  "Layer-Control: touchAction:none nur noch am Button — Panel scrollt wieder auf Mobile!",
  "Layer-Control: Outside-Click prüft containerRef statt panelRef — kein Flicker mehr beim Button-Klick",
  "Layer-Control: overscroll-contain verhindert Scroll-Bubbling zur Karte",
  "Error-Boundary: Per-Page Boundaries (Karte, Hunting, Logbuch, Einstellungen, Hilfe)",
  "Error-Boundary: name-Prop für gezielte Fehleranzeige + Neu-laden-Button pro Seite",
  "Karten-Fix: Layer verschwinden nicht mehr nach Aktivierung (eachLayer redraw entfernt)",
  "Karten-Fix: invalidateSize nur noch einmal pro Layer-Wechsel — keine Tile-Neuladung mehr",
  "Layer-Control: Aussenklick schliesst das Panel (Outside-Click Handler)",
  "Layer-Control: Panel bleibt stabil beim Drag-and-Drop (touchAction: none)",
  "Setup-Wizard: Dual-Flag-Check (setup_complete + wizard_completed) — erscheint nicht mehr erneut",
  "Setup-Wizard: safeStorage Wrapper verhindert Crash bei Private Browsing",
  "Stabilität: Global Error Handler (window.error + unhandledrejection) — kein White-Screen mehr",
  "Stabilität: ErrorBoundary bereits vorhanden um alle Hauptkomponenten",
  "Performance: Viewport-basiertes Laden bereits implementiert (ViewportDataLoader)",
  "Performance: Memoization bereits aktiv (useMemo für gefilterte Marker)",
  "Wavelog Fix: URLs (LAN+WAN) werden jetzt zuverlässig gespeichert (Debounce-Akkumulation)",
  "Wavelog Fix: onBlur Auto-Save beim Verlassen der Eingabefelder",
  "Wavelog Fix: station_info Fallback auf Station ID '1' (Wavelog 3.1.0 Bug Workaround)",
  "Wavelog Fix: Manuelle Station-ID Eingabe wenn station_info nicht verfügbar",
  "Wavelog Fix: Wahlschalter versteckt QRZ-Personal-Button wenn Backend = 'wavelog'",
  "Wavelog Fix: Club-QRZ-Button bleibt sichtbar (Ausnahme bei Club-Log-Filter)",
  "Wavelog Fix: Auto-Station-ID '1' wenn Settings geladen und keine Station-ID gesetzt",
  "Wavelog Fix: QSO-Save respektiert Wahlschalter (Wavelog Auto-Sync nach QSO-Save)",
  "Wavelog-Integration: Pro-User Settings (LAN+WAN URL, API Key, Station)",
  "Wavelog: Wahlschalter QRZ.com ODER Wavelog (nicht beides gleichzeitig)",
  "Wavelog: Ausnahme Club-QRZ bei Club-Log-Filter immer möglich",
  "Wavelog: Upload Button — alle nicht gesendeten QSOs an Wavelog senden",
  "Wavelog: Import Button — Delta-Sync mit lastfetchedid von Wavelog",
  "Wavelog: Permanent Sync — QSOs sofort an Wavelog senden (Auto-Sync)",
  "Wavelog: Offline Queue — QSOs offline loggen, automatisch bei Online gesendet",
  "Wavelog: Logbuch-Sync beim Öffnen — automatischer Delta-Import",
  "Wavelog: ADIF Konvertierung (QSO → ADIF → Wavelog API)",
  "Wavelog: Backend-Proxy vermeidet Mixed-Content Blocking (HTTP Server)",
  "Wavelog: Duplikat-Check beim Import (callsign + date + time)",
  "Hunting: 6-Tabs-Struktur (SOTA, POTA, WWFF, WWBOTA, Live Spot Activity, Alerts)",
  "Hunting: Keine Spot-Limits mehr — alle SOTA/POTA/WWFF/WWBOTA/DX-Spots werden angezeigt",
  "Hunting: SOTA API mit 200 Spots (3-Segment-URL /api/spots/200/all/all)",
  "Hunting: DX-Cluster speichert alle Spots (355 statt 100) — keine Slice-Limits",
  "Hunting: Spothole SIG-Spots limit=500 (war 100)",
  "Hunting: DxSpot Entity limit=500 (war 50) — merged ohne Slice",
  "Hunting: SOTA QRT/RBNHOLE-Filter aktiv (Backend + Frontend)",
  "Hunting: Alerts-Tab kombiniert SOTA-Alerts + WWFF-Agendas (260 geplante Aktivierungen)",
  "Hunting: POTA/WWBOTA-Hinweis im Alerts-Tab (keine geplante API verfügbar)",
  "UI: Gerätespezifische QSO-Button-Position (desktop/tablet/mobile getrennt)",
  "UI: Feldbreiten pro Gerät konfigurierbar (Settings → Feldbreiten pro Gerät)",
  "UI: UserHuntingSettings.ui_settings Entity-Feld für server-side Sync",
  "Karten-Fix: Stabile Container-Keys verhindern _leaflet_pos-Fehler bei View-Wechseln",
  "Zoom-Animation deaktiviert: Keine Abstürze mehr beim Schliessen von Modalen",
  "QSO-Weltkarte: Sauberes Umschalten zwischen Globus und 2D-Karte",
  "Hunting-Modul: Live DX-Spots mit GPS-basierter Distanz- und Azimuth-Berechnung",
  "Hunting-Modul: Propagation-Dashboard mit Solar Flux, K-Index und Band-Conditions",
  "Hunting-Modul: Fox Hunting mit Peilung, Triangulation und GPS-Position",
  "Hunting-Modul: QSO direkt aus Spot loggen — Formular automatisch vorausgefüllt",
  "Hunting-Modul: QRZ-Lookup direkt aus der Spot-Tabelle per Klick auf Rufzeichen",
  "GPS-Tracking: Live-Position vom Gerät überschreibt statischen Stations-Locator",
  "Build-Optimierung: Vendor-Chunks aufgeteilt für schnelleres Laden",
];

// Data sources reference — used by Help page and menu.
export const DATA_SOURCES = [
  { name: "Spothole (Spots & Propagation)", url: "spothole.app/api/v2", count: "Live-Spots + Solar", schedule: "alle 30s (Live Stream)" },
  { name: "SOTA", url: "api2.sota.org.uk", count: "~181.658 Gipfel", schedule: "täglich 03:00 UTC" },
  { name: "POTA", url: "api.pota.app", count: "~89.650 Parks", schedule: "täglich 03:30 UTC" },
  { name: "WWFF", url: "wwff.co/wwff-data/wwff_directory.csv", count: ">1.000 Gebiete", schedule: "täglich 04:00 UTC" },
  { name: "IOTA", url: "iota-world.org", count: "1.178 Gruppen", schedule: "täglich 03:00 UTC" },
  { name: "WWBOTA", url: "api.wwbota.net", count: "Bunker weltweit", schedule: "täglich 04:30 UTC" },
  { name: "Burgen/Schlösser", url: "OSM + Wikidata", count: "weltweit", schedule: "täglich 04:30 UTC" },
  { name: "Repeater", url: "RepeaterBook + hearham.com", count: ">22.000 Relais", schedule: "täglich 05:00 UTC" },
  { name: "Leuchttürme", url: "Wikidata SPARQL + Fallback", count: "weltweit", schedule: "täglich 05:30 UTC" },
  { name: "APRS", url: "aprs.fi API (API-Key)", count: "Stationen weltweit", schedule: "täglich 06:00 UTC" },
  { name: "TOTA", url: "swiss_csv + wwtota.com", count: "Antennen/Türme", schedule: "täglich 06:30 UTC" },
  { name: "FM-Funknetz", url: "fm-funknetz.de", count: "Talkgruppen", schedule: "täglich 06:30 UTC" },
];

// Privacy notice — short text shown in menu and help.
export const PRIVACY_NOTICE =
  "Diese App verarbeitet Standortdaten zur Kartenanzeige und speichert Cache-Daten lokal auf dem Gerät. Es werden keine personenbezogenen Daten an Server übertragen ausser den für die Daten-Synchronisation nötigen API-Abfragen.";