// App version and build number — compiled into the APK at build time.
// Version follows semantic versioning (Major.Minor.Patch).
// Build is a timestamp-based unique identifier (YYYYMMDDHHMM) generated at build.
//
// To create a new release build:
// 1. Increment VERSION below
// 2. Update BUILD to the current timestamp (YYYYMMDDHHMM format)
// 3. Add a changelog entry to CHANGELOG below
// 4. The menu drawer displays these values automatically (offline-readable)

export const APP_VERSION = "0.951";

// Build number — timestamp-based, unique per build.
// Format: YYYYMMDDHHMM (e.g. 202608132237)
// Update this before each APK build to the current timestamp.
export const APP_BUILD = "202609251056";

// Changelog — short list of changes for the current version.
// Displayed in the hamburger menu under the version number.
export const APP_CHANGELOG = [
  "v0.957: WAVELOG-SYNC-FLAG — Defensive Reparatur: Records mit wavelog_sync_date aber wavelog_synced=false werden nicht erneut gesendet, sondern nur das Flag repariert (verhindert doppelte Uploads)",
  "v0.957: WAVELOG-SYNC-FLAG — uploadToWavelog (manueller Upload): Defensive Prüfung vor Upload — wavelog_sync_date gesetzt → Flag reparieren statt erneut senden",
  "v0.957: WAVELOG-SYNC-FLAG — sendQsoToWavelog (Auto-Sync/Offline-Queue): Gleiche defensive Prüfung — verhindert doppelte Uploads bei durch Import überschriebenem Flag",
  "v0.957: WAVELOG-SYNC-FLAG — permanent_sync Step B (Backend): toExport aufgespalten in toRepair (sync_date gesetzt) + toSend (kein sync_date) — toRepair bekommt nur Flag-Reparatur, toSend wird hochgeladen",
  "v0.957: CH-RELAIS-LINKS — QTH-Map: USKA-remarks enthalten Standortnamen (HochYbrig, Tamaro, Chestenberg), keine Callsigns — QTH→Repeater-Map aus USKA-Daten für zuverlässiges Link-Target-Matching",
  "v0.957: CH-RELAIS-LINKS — Link-Matching: 3-stufige Suche (1. Callsign, 2. QTH-Map, 3. location_name case-insensitive) — case-sensitivity Bug im location_name-Fallback korrigiert",
  "v0.957: CH-RELAIS-LINKS — Cleanup: RepeaterLink-Tabelle vor Sync bereinigt — Backup in AppSetting, Duplikate (sortierter from→to Key) und Selbst-Verbindungen (from===to) gelöscht",
  "v0.957: CH-RELAIS-LINKS — KEINE neuen Repeater-Records aus USKA-Liste importiert (nur Link-Logik auf vorhandenem Bestand)",
  "v0.957: UI-CLAMPING — DraggableMapButton: requestAnimationFrame für resize-Handler + tatsächliche Button-Dimensionen via ref statt size-prop",
  "v0.957: UI-CLAMPING — useDraggableButton: requestAnimationFrame für resize-Handler (Layout muss settled sein vor Clamping)",
  "v0.957: UI-CLAMPING — useDraggablePosition: requestAnimationFrame für resize-Handler",
  "v0.956: WAVELOG-ZEIT-BUG — qsoToAdif: time_start Padding auf 6 Stellen (HHMMSS) — 'HH:MM' (4 Ziffern) wurde als <time_on:6> mit nur 4 Zeichen gesendet → ADIF-Längen-Mismatch korruptierte Datensatz → Wavelog defaultete auf 00:00",
  "v0.956: WAVELOG-ZEIT-BUG — permanent_sync (Backend): Gleicher Padding-Fix für serverseitigen ADIF-Export",
  "v0.956: WAVELOG-ZEIT-BUG — LogEntryForm: Default-Zeit jetzt HH:MM:SS (vorher HH:MM = 4 Ziffern ohne Doppelpunkt = ADIF-Korruption)",
  "v0.956: WAVELOG-ZEIT-BUG — LogEntryForm: 'Jetzt'-Buttons für Start+Endzeit liefern jetzt HH:MM:SS",
  "v0.956: QRZ-EXPORT — Log.jsx handleExport + handleQrzUpload: <time_on:4> mit replace(':', '') (nur erstes Zeichen) → <time_on:6> mit replace(/:/g, '') + padEnd(6, '0') + TIME_OFF hinzugefügt",
  "v0.955: RESILIENZ — fetchWithRetry Shared-Utility (3 Versuche, 10s/30s/60s Backoff) für alle Sync-Funktionen bei 5xx/Timeout/Netzwerkfehler",
  "v0.955: RESILIENZ — fetchCHRepeaterLinks: USKA-Fetch mit Retry — transienter 502 wird jetzt automatisch retried statt sofort zu fehlschlagen",
  "v0.955: RESILIENZ — fetchLlotaRefs: LLOTA-API + Country-Stats mit Retry — transiente Fehler werden retried",
  "v0.955: RESILIENZ — fetchLlotaSpots: LLOTA + Spothole mit Retry — CRITICAL FIX: Delete alte Spots erst NACH erfolgreichem Fetch (vorher: Delete vor Fetch = Datenverlust bei Fehlschlag)",
  "v0.955: OVERPASS — fetchCastlesOverpass: Per-Request-Timeout 85s (unter 100s Cloudflare-524-Limit), 2 Runden Mirror-Rotation mit 10s/30s Backoff, out center bereits vorhanden",
  "v0.955: COVERAGE — calculateRepeaterCoverage: batch_limit 50→15 (verteilt Rechenlast über mehrere kleine Läufe), Resume-Cursor in AppSetting für Fortschritts-Tracking",
  "v0.955: 0-EINTRÄGE — HTTP 200 + gültiges leeres Ergebnis = success (0), KEINE Warnung — LLOTA-Spots können legitim 0 sein",
  "v0.955: DEGRADED — Erst nach 3 aufeinanderfolgenden 0/Fehler-Läufen → Status 'degraded' + Warnung (statt sofortiger Warnung bei einzelnen 0-Läufen)",
  "v0.955: USKA-RELAUNCH — fetchCHRepeaterLinks auf neue USKA-Website umgestellt (alte URL /hb-repeater-voice-list/ liefert 404 seit 16.09. Relaunch)",
  "v0.955: USKA-RELAUNCH — JSON-API-Endpunkt https://uska.ch/wp-json/uska/v1/repeaters als Primärquelle (308 Repeater, strukturierte Felder: tx/rx/call/qth/kanton/locator/alt/type/dmr/dstar/c4fm/rx_tone/tx_tone/status/notes)",
  "v0.955: USKA-RELAUNCH — HTML-Parsing als Fallback (neue 16-Spalten-Tabelle, neue URL /de/funkamateure/repeater-liste-und-bandplaene/hb-voice-repeater-list/)",
  "v0.955: USKA-RELAUNCH — Modi-Extraktion nutzt strukturierte dmr/dstar/c4fm-Boolean-Felder statt Remarks-Parsing — zuverlässiger",
  "v0.955: USKA-RELAUNCH — CTCSS/DCS-Ton aus rx_tone-Feld (vorher: Remarks-Parsing) — DCS#023 Format wird korrekt erkannt",
  "v0.955: USKA-RELAUNCH — Status-Mapping: qrv=on-air, qrx=testing, planned=testing, qrt=off-air (vorher: numerisch 0/1/2/3)",
  "v0.955: BUCHHALTUNG — extractCount erkennt jetzt saved/fetched/merged/new_castles/linksCreated/calculated/countriesSaved — last_count wird korrekt gepflegt statt auf 0 zu stehen",
  "v0.954: UPSERT-SCHUTZ — Wavelog-Import (import, full_import, permanent_sync) und QRZ-Club-Import nutzen echten Upsert statt Skip-Dedup — existierende Records werden aktualisiert, nicht übersprungen",
  "v0.954: UPSERT-SCHLÜSSEL — (operator_callsign, callsign, qso_date, time_start, log_type, club_callsign) — verhindert Duplikate bei wiederholten Imports zuverlässig",
  "v0.954: FULL-IMPORT — Startet ab wavelog_last_fetch_id (bzw. 0) wie delta sync — gleicher Upsert-Pfad für beide Modi",
  "v0.954: BULKDELETE — bulkDeleteLogs unterstützt Filter-Interface ({operator_callsign, log_type}) neben ID-Listen — Service-Rolle für künftige Bereinigungen",
  "v0.954: SHARED MODULE — logUpsert.ts mit upsertKey/loadExistingLogMap/upsertLogs — verwendet von allen Import-Pfaden",
  "v0.953: CONTEST-FILTER — Mode-Filter verwendet modes-Array (NOT mode_families die NULL sind) — OR-Logik: Contest matcht wenn ANY ausgewählter Modus in modes enthalten",
  "v0.953: CONTEST-FILTER — Band-Filter verwendet bands-Array (NOT band_families die NULL sind) — OR-Logik mit VHF+ Sonderbehandlung (2m, 70cm, 23cm, etc.)",
  "v0.953: CONTEST-FILTER — Zeit-Filter: 'Aktuell' (Default) = laufende + zukünftige, neu 'Vergangene' Option für vergangene Contests",
  "v0.953: CONTEST-FILTER — Sortierung nach Modus verwendet modes-Array, Anzeige verwendet modes/bands direkt (kein Fallback auf NULL-Felder mehr)",
  "v0.951-HF3: WAVELOG-BUTTONS — Manuelle Wavelog-Buttons (Import + Voll-Import) sind IMMER klickbar — wavelog_enabled=false deaktiviert sie nicht mehr",
  "v0.951-HF3: WAVELOG-BUTTONS — disabled-Logik entfernt: nur noch importing/fullImporting deaktiviert — keine Pause-Flags mehr in der disabled-Prüfung",
  "v0.951-HF3: WAVELOG-IMPORT — importFromWavelog/fullImportFromWavelog prüfen NICHT mehr wavelog_enabled — nur noch API-Key als echte Voraussetzung",
  "v0.951-HF3: QRZ-CLUB-SYNC — Button sichtbar UND klickbar für ALLE User (nicht mehr isAdmin-only) — nicht durch Pause blockiert",
  "v0.951-HF3: ADIF-IMPORT — Button war bereits immer sichtbar/klickbar — keine Änderung nötig",
  "v0.951-HF3: REGEL — Pause-Flags (sync_paused, wavelog_enabled, wavelog_auto_sync) steuern NUR automatische Hintergrund-Syncs — manuelle Buttons sind immer funktionsfähig",
  "v0.951-HF2: ADIF-WARNUNG — Private Callsign wird aus 'Meine Station' (localStorage hb9om_my_callsign) gelesen, NICHT aus club_callsign_config — falsches Feld korrigiert",
  "v0.951-HF2: ADIF-WARNUNG — Fehlertext korrigiert: 'In Einstellungen → Meine Station setzen' (vorher falsch 'Club-Station')",
  "v0.951-HF2: ADIF-WARNUNG — Bei CLUB-Import wird keine Private-Callsign-Warnung mehr angezeigt — Club-QSOs brauchen club_callsign=HB9OM, nicht die private Callsign",
  "v0.951-HF2: SYNC-PAUSE — sync_paused (per-User UND global) blockiert NUR automatische Hintergrund-Syncs — manuelle Buttons bleiben aktiv",
  "v0.951-HF2: SYNC-PAUSE — Wavelog-Buttons bleiben sichtbar (nur disabled wenn Wavelog nicht konfiguriert) — Pause entfernt keine Buttons aus der UI",
  "v0.951-HF2: QRZ-CLUB — Manueller Club-Import funktioniert auch mit globalem AppSetting sync_paused=true — manual-Flag umgeht isSyncPaused komplett",
  "v0.951-HF: QRZ-CLUB-MANUELL — Manueller Club-Import (Button) wird NICHT durch sync_paused blockiert — nur automatische Hintergrund-Syncs respektieren die Pause",
  "v0.951-HF: QRZ-CLUB-MANUELL — fetchQrzClubLog akzeptiert { manual: true } im Request-Body um Sync-Pause zu umgehen",
  "v0.951-HF: ADIF-TYP-AUSWAHL — Import-Dialog zeigt Typ-Auswahl (Privat vs Club) VOR dem Datei-Upload — manuelle Auswahl ist führend",
  "v0.951-HF: ADIF-TYP-AUSWAHL — Privat: log_type='private', is_clubstation=false, operator_callsign=private_callsign (HB3YNF aus AppSetting)",
  "v0.951-HF: ADIF-TYP-AUSWAHL — Club: log_type='club', is_clubstation=true, club_callsign='HB9OM', club_operator_callsign aus ADIF OPERATOR-Feld",
  "v0.951-HF: ADIF-TYP-AUSWAHL — applyImportType() Funktion überschreibt ADIF-eigene STATION_CALLSIGN/MY_SIG bei manueller Auswahl",
  "v0.951-HF: ADIF-TYP-AUSWAHL — Warnung bei fehlender private_callsign Konfiguration (Einstellungen → Club-Station)",
  "v0.951-HF: APPSETTING — private_callsign='HB3YNF' zu club_callsign_config hinzugefügt — für ADIF-Import und zukünftige Verwendung",
  "v0.951-HF: LOG-FILTER — Club-Ansicht strikt: log_type='club' AND is_clubstation=true AND club_callsign='HB9OM' — keine privaten QSOs mehr in Club-Ansicht",
  "v0.951-HF: LOG-FILTER — Privat-Ansicht: alles NIC-Club — keine Club-QSOs mehr in Privat-Ansicht, keine Überschneidung",
  "v0.951-HF: QRZ-CLUB-IMPORT — fetchQrzClubLog verwendet Club-API-Key 2B86-9159-3CAA-B13D (HB9OM-Logbuch), NICHT privaten QRZ_API_KEY",
  "v0.951-HF: QRZ-CLUB-IMPORT — operator_callsign = OPERATOR-Feld aus QRZ-ADIF (tatsächlicher OM), nicht mehr HB9OM",
  "v0.951-HF: QRZ-CLUB-IMPORT — Within-batch Dedup verhindert doppelte Importe bei mehrfach gelieferten QSOs",
  "v0.951-HF: QRZ-CLUB-IMPORT — Letzter Sync-Zeitstempel + Import-Zahl in AppSetting gespeichert, in UI sichtbar",
  "v0.951-HF: DUBLETTEN — 15 doppelte Club-QSOs vom 09.04.2026 (MM7CEH 7x, SP5XTY 9x, MM7CEH 2x) bereinigt auf je 1x",
  "v0.951-HF: GETCLUBLOG — Strikter Filter log_type+is_clubstation+club_callsign, kein $or-Fallback mehr",
  "v0.951-RC: GRENZEN — WWFF- und LLOTA-Grenzen jetzt über pota-map.fr API (gleicher Endpoint wie POTA, gleicher Cache mit program-Feld)",
  "v0.951-RC: GRENZEN — DLFF-0001 echtes Polygon, HBFF-0001 echtes Polygon, LLCH-0002 'Lake Geneva' echtes Polygon — alle bestätigt",
  "v0.951-RC: GRENZEN — WWFF/LLOTA ohne Grenze zeigen gestrichelten 'ca.'-Kreis (identisch wie POTA-Fallback)",
  "v0.951-RC: GRENZEN — WwffPoint-Entity um boundary/boundary_source-Felder erweitert, LlotaRef.polygon wird von pota-map.fr aktualisiert",
  "v0.951-RC: 3D-TOGGLE — 3D-Gelände-Toggle direkt in der Hauptkarte (topright, Berg-Icon) — keine separate 3D-Seite mehr nötig",
  "v0.951-RC: 3D-TOGGLE — Terrain + 45° Pitch auf der MapLibre-GL-Basiskarte, alle Layer/Marker/Popups/Filter bleiben voll bedienbar",
  "v0.951-RC: 3D-TOGGLE — Umschalten 2D↔3D ohne Reload, Zustand wird in localStorage gespeichert",
  "v0.951-RC: QRZ-CLUB — Club-Log-Upload wieder aktiv — pro User individueller QRZ-API-Key in persönlichen Einstellungen",
  "v0.951-RC: QRZ-CLUB — uploadToQrz verwendet user.qrz_club_api_key (Fallback auf globale Config/Secret)",
  "v0.951-RC: QRZ-CLUB — UI: Key-Eingabefeld in Einstellungen → Meine Station → QRZ Club-Log Upload",
  "v0.952: POTA-GRENZEN — pota-map.fr als neue autoritative Datenquelle für Park-Grenzen weltweit (getestet: CH/DE/US)",
  "v0.952: POTA-GRENZEN — PotaBoundaryCache-Entity cached GeoJSON-Grenzen + has_boundary-Flag (null-Ergebnisse werden gecacht)",
  "v0.952: POTA-GRENZEN — getPotaBoundary Backend-Funktion mit Cache-Lookup + pota-map.fr API + PotaPoint-Persistierung",
  "v0.952: POTA-GRENZEN — Echte Polygone durchgezogen (solid), Parks ohne Grenze gestrichelter Kreis mit 'ca.'-Kennzeichnung",
  "v0.952: POTA-GRENZEN — DACH-Prefetch (CH/DE/AT/LI) für sofortige Grenzanzeige in der Heimat-Region",
  "v0.952: REPEATER-CLEANUP — 16'626 null-Koordinaten-Records gelöscht (vorher 17'836, jetzt 5'000 valide Relais)",
  "v0.952: REPEATER-CLEANUP — fetchRepeaters buildRecord gibt null zurück bei invaliden Koordinaten — bulkCreate überspringt sie",
  "v0.952: REPEATER-CLEANUP — ReferenceData repeater total_count korrigiert (17'836 → 5'000 echte Entity-Anzahl)",
  "v0.952: KOORD-GUARD — MobilActive.jsx filtert NaN/out-of-range Koordinaten vor haversine-Berechnung — keine NaN-Distanzen mehr",
  "v0.952: KOORD-GUARD — MobilMapView, RouteMapView, LiveMapView, RepeaterLayer, Map3D prüfen lat/lng auf null+NaN+Range — keine Map-Crashes mehr",
  "v0.952: POTA-GRENZEN — boundary-Feld in PotaPoint-Entity (Array von [lat,lng] Polygon-Punkten) — Grenzen werden gespeichert",
  "v0.952: POTA-GRENZEN — fetchPotaBoundary speichert gefundene Polygone in PotaPoint (Nominatim + Overpass + Nearest-Fallback)",
  "v0.952: POTA-GRENZEN — fetchSwissTopoBoundaries speichert BLN-Polygone in PotaPoint (bei reference-Übergabe)",
  "v0.952: POTA-GRENZEN — Grenz-Toggle prüft zuerst gespeicherte boundary — instant Anzeige ohne API-Aufruf bei erneutem Toggle",
  "v0.952: POTA-GRENZEN — boundary_source-Feld zeigt Quelle des Polygons (nominatim/overpass/swisstopo-bln)",
  "v0.951-HOTFIX3: MOBIL-SW — Early SW-Cleanup direkt in index.html (vor Module-Loading) — SW kann keine stale Chunks mehr servieren",
  "v0.951-HOTFIX3: 3D-LAYER — setLayoutProperty('visibility') für zuverlässiges Toggle-On/Off (vorher: Source-Data gelöscht → unzuverlässig)",
  "v0.951-HOTFIX3: 3D-POPUP — GeoJSON-Features haben jetzt alle Properties (points, altitude, country, frequency, band, mode etc.) — Popups nicht mehr leer",
  "v0.951-HOTFIX3: POTA-GRENZEN — BLN-Polygone durchgezogen (solid), Kreis-Fallback gestrichelt (dashed) — visuell unterscheidbar",
  "v0.951-HOTFIX3: POTA-GRENZEN — SwissTopo-Suche erweitert: BLN + BIOTOP + MOOR + AUEN (vorher nur BLN) — mehr Parks haben echte Polygone",
  "v0.951-DATA1: SCHEDULER-FIX — Daily Sync Checker Cron geändert auf */5 3-7 * * 1,4 (nur Mo/Do) — feuerte vorher jeden Tag 03:00-07:00 UTC",
  "v0.951-DATA1: SCHEDULER-FIX — dailyRefreshChecker prüft Wochentag (Mo/Do) bevor Quellen feuern — Belt-and-Suspenders Schutz",
  "v0.951-DATA1: SCHEDULER-FIX — DailyRefreshSchedule zurückgesetzt: Sonntag-Läufe gelöscht, next_run_utc auf Mo 14.09. gesetzt",
  "v0.951-DATA2: SOTA-UPSERT-FIX — refreshDataSource auf upsertPointsByCode umgestellt (vorher upsertPoints = Delete+Reimport → Duplikate bei Timeout)",
  "v0.951-DATA2: SOTA-UPSERT-FIX — createOnly-Option in upsertPointsByCode: überspringt Update-Phase, verhindert Worker-Crash bei 174k+ Records",
  "v0.951-DATA2: SOTA-UPSERT-FIX — fetchSOTA + fetchHBFF nutzen createOnly — nur fehlende Records werden erstellt, keine Updates",
  "v0.951-DATA2: SOTA-RESTORED — 182'279 unique SotaPoint, 0 Duplikate (vorher 157'353 unique, 15'000 durch alten Code-Pfad gelöscht)",
  "v0.951-DATA3: WWFF-DEDUP — 31'889 + 1'217 Duplikate gelöscht, 65'904 unique WwffPoint (vorher 97'796 mit Duplikaten)",
  "v0.951-DATA4: CASTLES-OVERPASS — Retry-Logik optimiert: 429/521 sofort nächstes Endpoint, 504/524 1x Retry mit 5s Delay",
  "v0.951-DATA4: CASTLES-OVERPASS — batch_limit/batch_offset Parameter für kleinere Länder-Batches (verhindert 524-Timeouts)",
  "v0.951-DATA5: DEDUP-SAFE — dedupReferencePoints wendet KEINE Normalisierung an — Matching exakt auf code-Feld wie vom Sync geschrieben",
  "v0.951-FIX1: SW-CACHE-FIX — Aggressive Cache-Bereinigung (löscht ALLE Caches, nicht nur workbox/base44) — keine intermittierenden White-Screens mehr",
  "v0.951-FIX1: SW-CACHE-FIX — Dynamic-Import-Fehler abgefangen (Failed to fetch dynamically imported module) — einmaliger Auto-Reload statt White-Screen",
  "v0.951-FIX1: SW-CACHE-FIX — Reload-Loop-Schutz durch sessionStorage Flag (nur 1 Reload pro Session)",
  "v0.951-FIX2: 3D-LAYER — Layer-/Filter-Popup im 3D-Modus: Style-Auswahl (Liberty/Bright/Dark) + alle Aktivitätszonen + Repeater-Layer",
  "v0.951-FIX2: 3D-LAYER — 8 Layer-Typen im 3D-Modus: SOTA, POTA, WWFF, Leuchtturm, IOTA, LLOTA, TOTA, Relais — GeoJSON mit Clustering",
  "v0.951-FIX2: 3D-LAYER — Style-Wechsel erzwingt Map-Neuaufbau (key=styleUrl) — saubere Layer-Initialisierung",
  "v0.951-FIX3: 3D-GELÄNDE — Terrain-Quelle auf US-Bucket umgestellt (elevation-tiles-prod statt EU-Bucket) — zuverlässigere Tile-Auslieferung",
  "v0.951-FIX3: 3D-GELÄNDE — mapLoaded State verhindert Race-Condition (setTerrain vor map.on('load') hatte keinen Effekt)",
  "v0.951-FIX3: 3D-GELÄNDE — maxzoom: 14 im Terrain-Source (Terrain-Tiles nur bis Zoom 14 verfügbar)",
  "v0.951-FIX4: POTA-GRENZEN — Point-in-Polygon-Test (Ray-Casting) stellt sicher dass BLN-Polygon den POTA-Punkt enthält",
  "v0.951-FIX4: POTA-GRENZEN — Progressive Toleranz (200m → 1000m → 2000m) verhindert Nachbar-Polygon-Zuordnung",
  "v0.951-FIX4: POTA-GRENZEN — Fallback auf nächstgelegenes Polygon wenn kein Polygon den Punkt enthält",
  "v0.951-HOTFIX: MOBIL-CRASH-FIX — L.maplibreGL undefined in Production-Builds (Tree-Shaking) — Raster-TileLayer Fallback hinzugefügt",
  "v0.951-HOTFIX: MOBIL-CRASH-FIX — resolveGoogleMapsLink parst Koordinaten direkt aus URL (keine Google Anti-Bot Redirects mehr)",
  "v0.951-HOTFIX: LEGACY-DELETE — 5 veraltete ReferenceData-Records bestätigt gelöscht (11 aktuelle Records verbleiben)",
  "v0.951: OPENFREEMAP — Karten-Tiles von OSM auf OpenFreeMap (Liberty Style) umgestellt — umgeht OSM Tile-Usage-Restriktionen",
  "v0.951: OPENFREEMAP — 3 Styles im Auswahl-Popup: Liberty (Default), Bright, Dark",
  "v0.951: OPENFREEMAP — Attribution 'OpenFreeMap © OpenMapTiles | Data from OpenStreetMap contributors' in UI und PDF-Export",
  "v0.951: SCHEDULER-FIX — Daily Sync Checker Workflow erstellt (alle 5 Min 03:00-07:00 UTC) — schliesst Lücke an Di/Mi/Fr/Sa/So",
  "v0.951: SCHEDULER-FIX — dailyRefreshChecker schreibt jetzt SyncLog-Einträge (trigger='scheduled') für Nachverfolgung",
  "v0.951: SOTA-DEDUP — 689k Duplikate entfernt, 180.079 unique SOTA-Summits verbleiben (0 Duplikate bestätigt)",
  "v0.951: PHASE2-3D — Neue 3D-Ansicht (MapLibre GL JS) mit Globus-Projektion, Pitch/Rotate-Gesten, Himmel/Atmosphäre",
  "v0.951: PHASE2-3D — 3D-Gebäude via fill-extrusion (Liberty Style), SOTA/POTA/WWFF-Marker als GeoJSON mit Clustering",
  "v0.951: PHASE2-3D — Eigener Menüpunkt '3D' in Bottom-Navigation + '3D-Ansicht öffnen' im Layer-Popup",
  "v0.951: PHASE2-GELÄNDE — 3D-Gelände (AWS Terrain Tiles, Terrarium-Encoding, EU-Bucket, Exaggeration 1.2) — Alpen in Relief",
  "v0.951: PHASE2-OFFLINE — Offline-Packs auf OpenFreeMap-Vektorkacheln (PBF) umgestellt — CH-Packs schrumpfen drastisch",
  "v0.951: PHASE2-OFFLINE — Bestehende Raster-Packs invalidiert (Pack v2) — 'Pack erneut herunterladen' Meldung",
  "v0.951: PHASE2-OFFLINE — MapLibreTileLayer unterstützt Offline-Modus via transformRequest + IndexedDB Blob-Cache",
  "v0.951: SOTA-UPSERT-FIX — upsertPointsByCode nutzt Cursor-basierte Paginierung ($lt auf created_date) — keine Duplikate mehr",
  "v0.951: SOTA-UPSERT-FIX — Zähler-Korrektur: ReferenceData zeigt echten Bestand (182.279 statt 40.000) — 8s-Budget entfernt",
  "v0.951: SOTA-UPSERT-FIX — fetchTota, fetchIOTA, fetchLlotaRefs auf upsertPointsByCode umgestellt — keine Duplikate bei Timeout",
  "v0.951: LEGACY-DELETE — 5 veraltete ReferenceData-Records gelöscht (server-seitig, Service-Rolle) — 11 aktuelle Records",
  "v0.95: REGISTRATION-FIX — User-Entity 'role' Default-Wert auf 'user' gesetzt — verhindert Registrierungsfehler bei neu verifizierten Benutzern",
  "v0.95: REGISTRATION-FIX — Register.jsx prüft jetzt access_token vor User-Record-Erstellung — verhindert 'No access token' Fehler",
  "v0.95: REGISTRATION-FIX — Demo-Passwort von 'demo123' auf 'demo1234' korrigiert",
  "v0.95: SOTA-DEDUP — Paginierte Bereinigung gestartet: 274k Duplikate gelöscht, 159835 unique Codes identifiziert (2 Passes)",
  "v0.95: LEGACY-CLEANUP — Alle ReferenceData-Records vom 28.07 entfernt — aktuelle 11 Records sauber",
  "v0.95: SCHEDULER-STATUS — 25 Quellen terminiert (21 aktiv), nächster Batch-Lauf Montag 14.09. 01:00 UTC",
  "v0.9047: REPEATER-DEDUP — Serverseitige Callsign+Frequenz Deduplikation entfernt 193 Duplikate in EU-Priority-1 (DB0ROE, DB0SKF, DB0LBB, DB0HEL, DO0RM)",
  "v0.9047: REPEATER-DEDUP — Dedup-Logik behält Record mit gültigem CTCSS-Tone ODER Koordinaten ODER on-air-Status (vorher: zufälliger Record)",
  "v0.9047: REPEATER-DEDUP — 7 echte Duplikate (gleiche Callsign+Frequenz) eliminiert, 0 verbleibende Duplikate verifiziert",
  "v0.9047: REFERENCE-DATA-KORREKTUR — Repeater total_count von 43242 (Batch-Zähler) auf 14797 (echte Entity-Anzahl) korrigiert",
  "v0.9047: REFERENCE-DATA-KORREKTUR — TOTA total_count von 12196 auf 11607 (echte Entity-Anzahl) korrigiert",
  "v0.9047: REFERENCE-DATA-KORREKTUR — Lighthouse total_count von 1675 auf 1669 (echte Entity-Anzahl) korrigiert",
  "v0.9047: REFERENCE-DATA-KORREKTUR — IOTA total_count von 228 auf 1178 (echte Entity-Anzahl) korrigiert",
  "v0.9047: REPEATER-WELT-SYNC — Alle 6 Regionen synchronisiert: EU-P1 (1804), EU-P2 (1251), UK (748), USA (51 Staaten, ~18k), SA (1542), Ozeanien (841)",
  "v0.9047: REPEATER-WELT-SYNC — 14797 Repeater total, 6265 mit Koordinaten (42.3%), 8532 ohne Koordinaten",
  "v0.9047: POTA-DUPLIKATE — 150000+ POTA-Records gefunden (44278 unique Codes = 11.4% Duplikate) — separate Bereinigung erforderlich",
  "v0.9046: REPEATER-MAPPING-FIX (3. Versuch) — Tone-Parsing extrahiert jetzt CTCSS aus 'CC 1 67.0' (vorher: 'CC 1 67.0' als Tone gespeichert)",
  "v0.9046: REPEATER-MAPPING-FIX — DCS-Code wird aus beliebigen Tone-Feldern extrahiert (D### Pattern), nicht nur wenn das ganze Feld DCS ist",
  "v0.9046: REPEATER-MAPPING-FIX — json-import-Records werden NICHT mehr übersprungen — ihre Koordinaten sind wertvoller Fallback",
  "v0.9046: REPEATER-MAPPING-FIX — Callsign-basierte Koordinaten-Fallback: DB0REU 70cm bekommt Koords von DB0REU 23cm (gleicher Standort)",
  "v0.9046: REPEATER-MAPPING-FIX — Two-Map-Strategie: existingBySourceId (exakt) + existingByCallsign (Cross-Band-Fallback)",
  "v0.9046: REFERENCE-DATA-FIX — total_count ist jetzt die ECHTE Entity-Record-Anzahl (gecountet), nicht der Batch-Zähler",
  "v0.9046: REFERENCE-DATA-FIX — upsertPoints und upsertPointsByCode zählen Entity-Records nach dem Upsert (8s Zeitbudget)",
  "v0.9045: REPEATER-FIX — buildRecord erhält jetzt auch tone und locator aus existingCoordsMap (vorher nur DCS, tone wurde mit leer überschrieben)",
  "v0.9045: REPEATER-FIX — DETAIL_PER_COUNTRY von 50 auf 500 erhöht (vorher nur 50 Detailseiten pro Land = nur 50 hatten Koordinaten)",
  "v0.9045: REPEATER-FIX — parseRepeaterDetail extrahiert jetzt tone und DCS von Detailseiten (vorher fehlten diese Felder komplett)",
  "v0.9045: REPEATER-FIX — existingCoordsMap speichert jetzt ALLE Records (nicht nur die mit Koordinaten) — tone/dcs/locator werden immer erhalten",
  "v0.9045: REPEATER-FIX — Koordinaten-Extraktion erweitert: L.marker, setView, data-lat/data-lng Patterns hinzugefügt",
  "v0.9045: REFERENCE-DATA-FIX — upsertPoints setzt total_count nicht mehr auf 0 wenn alle Batches fehlschlagen (vorher: ReferenceData zeigte 0 obwohl 90k Points in DB)",
  "v0.9045: REFERENCE-DATA-FIX — upsertPoints und upsertPointsByCode löschen jetzt Duplikat-ReferenceData-Records (vorher: alte + neue Records nebeneinander)",
  "v0.9045: NAVIGATION-FIX — Menü-Leiste unten: min 48x48px Touch-Target (vorher 44px), z-index 1100 (vorher 1000), touch-manipulation aktiviert",
  "v0.9045: NAVIGATION-FIX — Icons von 4px auf 5px vergrößert, justify-center + py-2 für volle Klickfläche",
  "v0.9045: INFO-MAIL — Bei jedem geplanten Sync-Lauf (Montag + Donnerstag) geht eine aggregierte Mail an thueler.daniel@gmail.com",
  "v0.9045: INFO-MAIL — Inhalt: alle Quellen mit Status/Anzahl/Dauer/Fehlern, eine Mail pro Lauf (nicht pro Quelle)",
  "v0.9045: INFO-MAIL — Kein Versand bei manuellen Syncs (nur scheduled), Duplikat-Schutz durch AppSetting-Marker",
  "v0.9044: SCHEDULER-REPARATUR — dailyRefreshOrchestrator setzt weekly_days jetzt ['Monday','Thursday'] für EU-Relais-Quellen (vorher nur ['Monday'] → Donnerstag-Sync lief nie)",
  "v0.9044: SCHEDULER-REPARATUR — repeater_eu_priority1, eu_priority2, uk, fm_funknetz, ch_repeater_links laufen jetzt auch am Donnerstag (03:00-04:00 UTC Teilsync)",
  "v0.9044: REPEATER-KOORDINATEN-FIX — fetchRepeaters speichert existingCoordsMap VOR dem Löschen und stellt lat/lng aus bestehenden Records wieder her (niemals null überschreiben)",
  "v0.9044: REPEATER-KOORDINATEN-FIX — DCS-Werte aus bestehenden Records werden erhalten wenn RepeaterBook keine neuen liefert",
  "v0.9044: REPEATER-KOORDINATEN-FIX — Locator→Koordinaten Ableitung bleibt aktiv, existingCoordsMap als zweite Fallback-Stufe",
  "v0.9044: TOTA-BATCH-SAVE — fetchTota worldwide speichert in 100er-Batches mit per-Batch Fehlerbehandlung (vorher upsertPointsByCode mit MongoDB-Timeout)",
  "v0.9044: TOTA-BATCH-SAVE — Delete-then-create Pattern ersetzt upsertPointsByCode (kein Laden aller existing Records nötig = keine MongoDB-Timeouts)",
  "v0.9044: LLOTA-STATUS-FIX — Leere Spot-Arrays (HTTP 200, 0 Spots) werden als OK gewertet, nicht als FAIL",
  "v0.9044: HB9-DX-CLUSTER — ham-radio.ch:7300, hb9bza.net:7300, spider.ham-radio.ch:7300 deaktiviert (raw TCP nicht unterstützt)",
  "v0.9043: CONTEST-EIGENE TABELLE — Contest-Bereich ist kein Tab in der Hunting-Tabelle mehr, sondern eine eigenständige Tabelle/Ansicht",
  "v0.9043: CONTEST-EIGENE TABELLE — Sortierbare Spalten: Name, Sponsor, Modus, Bänder, Datum/Zeit (UTC+lokal), Dauer, Status/Countdown",
  "v0.9043: CONTEST-EIGENE TABELLE — Standard-Sortierung Datum aufsteigend; sortierbar nach Name, Modus, Dauer",
  "v0.9043: CONTEST-EIGENE TABELLE — Zeilen-Klick öffnet Detail-Ansicht (alle Felder + Regeln-Link)",
  "v0.9043: CONTEST-EIGENE TABELLE — Countdown-Zusammenfassung (On the Air + Nächste 7 Tage) oben im Fenster erhalten",
  "v0.9043: ERWEITERTE SUCHE — Textsuche nach Contest-Name UND Sponsor (Live-Filter während Eingabe)",
  "v0.9043: ERWEITERTE SUCHE — Modus-Filter (CW/SSB/FM/RTTY/Digital/FT8-FT4/Mixed) Mehrfachauswahl",
  "v0.9043: ERWEITERTE SUCHE — Band-Filter (160m-6m/VHF+) Mehrfachauswahl, Dauer-Filter (<2h/2-12h/12-24h/>24h)",
  "v0.9043: ERWEITERTE SUCHE — Zeit-Filter (Alle/Jetzt aktiv/7 Tage/30 Tage/90 Tage), Sponsor-Dropdown",
  "v0.9043: ERWEITERTE SUCHE — Alle Filter UND-verknüpft, Zurücksetzen-Button, Treffer-Anzeige",
  "v0.9043: API-MAPPING — Neue Felder: verified, can_enter, duration_bucket, mode_families, band_families",
  "v0.9043: API-MAPPING — duration_bucket für Dauer-Filter, mode_families/band_families für Modus/Band-Filter",
  "v0.9042: DCS-DATENLÜCKE FIX — dcs-Feld fehlte im Update-Pfad von importRepeaterJson (wurde nur bei neuen Datensätzen gesetzt, nicht bei Updates)",
  "v0.9042: DCS-DATENLÜCKE FIX — repeaterImportMapping prüft jetzt mehrere Feldnamen (dcs, DCS, Dcs, squelch, encode) für DCS-Codes",
  "v0.9042: DCS-DATENLÜCKE FIX — Re-Sync der Repeater-Quellen befüllt dcs-Felder automatisch (DCS aus tone-Feld wird separiert)",
  "v0.9042: CONTESTCLOCK-INTEGRATION — Neue Contest-Entity + fetchContests Backend-Funktion (contestclock.com API, CC BY 4.0, 941 Contests 2026)",
  "v0.9042: CONTESTCLOCK-INTEGRATION — Neues ContestPanel im Hunting-Modul: 'On the Air' (aktiv mit Countdown) + 'Nächste 7 Tage' (kommend)",
  "v0.9042: CONTESTCLOCK-INTEGRATION — Modus-Filter (CW, SSB, RTTY, Digital, FM) im ContestPanel, Auto-Refresh 60s, Offline-Cache aus DB",
  "v0.9042: CONTESTCLOCK-INTEGRATION — 'Contests' Tab in der Activity-Bar (SOTA/POTA/WWFF/LLOTA/Alerts/Contests)",
  "v0.9042: QRZ-CLUB-ENTFERNUNG — Club-QRZ-API-Key-Eingabe und Club-QRZ-Login entfernt (nur noch persönliches QRZ-Login)",
  "v0.9042: QRZ-CLUB-ENTFERNUNG — 'QRZ Club' Download-Button entfernt (Club-QRZ-Login entfernt)",
  "v0.9042: QRZ-CLUB-ENTFERNUNG — 'QRZ Club Upload' Button deaktiviert (grau, Tooltip 'Club-Upload derzeit deaktiviert')",
  "v0.9042: QRZ-CLUB-ENTFERNUNG — Club-Logging-Datenstruktur (is_clubstation, club_callsign) UNVERÄNDERT erhalten",
  "v0.9041: KARTE SCHWARZ FIX — h-[100dvh] overflow-hidden statt min-h gibt dem Flex-Container eine definite Höhe → Karte rendert wieder",
  "v0.9041: KARTE SCHWARZ FIX — map.invalidateSize() nach 100ms + 500ms ruft Leaflet auf, die Kacheln neu zu layouten",
  "v0.9041: DCS FIX — DCS-Feld wird jetzt beim Import gemappt (RepeaterBook JSON, HTML-Scraper, US-API, Hearham, UK-Parser)",
  "v0.9041: DCS FIX — buildRecord in fetchRepeaters übergibt dcs an die DB (vorher wurde das Feld ignoriert)",
  "v0.9041: DCS FIX — Backward-Compat: DCS-Code im tone-Feld wird erkannt und als DCS angezeigt (z.B. 'D023' im Tone-Feld)",
  "v0.9041: DCS FIX — Hearham encode-Feld wird aufgeteilt: CTCSS → tone, D023 → dcs",
  "v0.9041: DCS FIX — UK-Parser extrahiert DCS aus dem Popup-Text (DCS: D023)",
  "v0.9040: DCS-Code-Anzeige — DCS (Digit-Coded Squelch) wird NEBEN dem Tone angezeigt (z.B. 'Tone: 88.5 | DCS: D023')",
  "v0.9040: DCS-Code-Anzeige — Relais kann Ton ODER DCS ODER beides ODER keins haben — alle Fälle korrekt dargestellt",
  "v0.9040: DCS-Code-Anzeige — Neues Feld 'dcs' in der Relais-DB (z.B. D023, D023N, D023I)",
  "v0.9040: Felder entfernt — Path Loss / ITM Loss / Clutter aus der Live-Anzeige entfernt (Berechnung im Backend bleibt)",
  "v0.9040: Felder entfernt — Titel 'Aktuell empfohlener Repeater' entfernt (keine Überschrift mehr über der Anzeige)",
  "v0.9040: Felder entfernt — Fresnel und Distanz am unteren Rand entfernt (Distanz steht bereits weiter oben)",
  "v0.9040: Abdeckungszeile — Repeater- und Eigene-Abdeckung auf gleicher Höhe mit Stop-Button (eine Zeile)",
  "v0.9040: Abdeckungszeile — 'Live'-Angabe in der ersten Zeile entfernt (wird nicht benötigt)",
  "v0.9040: Ein-Bildschirm-Layout — Relais-Angaben (oben) + Karte (unten) passen zusammen auf einen Handy-Bildschirm",
  "v0.9040: Ein-Bildschirm-Layout — Nur die Relais-Liste (darunter) erfordert Scrollen",
  "v0.9040: Ein-Bildschirm-Layout — Karte bekommt flex-1 (min 35vh), unnötige Abstände/Paddings reduziert",
  "v0.9040: ITM-Qualität inline — Badge + dBm in derselben Zeile wie Distanz/Azimuth (kompakt)",
  "v0.9039: CTCSS-Ton FIX — Ton wird wieder NEBEN DEM Offset angezeigt (vorher: neben Frequenz, oft übersehen)",
  "v0.9039: CTCSS-Ton FIX — Ton-Feld immer sichtbar (Platzhalter '—' bei Relais ohne Ton, vorher: Feld verschwand komplett)",
  "v0.9039: CTCSS-Ton FIX — Layout: Offset und Tone in derselben Zeile, gut lesbar für Auto-Bedienung",
  "v0.9038: Zoom-Button FIX — Hunting-Karte hatte zoomControl={false} ohne eigene Zoom-Controls → KEINE Zoom-Buttons sichtbar",
  "v0.9038: Zoom-Button FIX — zoomControl={true} wiederhergestellt auf Hunting-Karte (Standard Leaflet-Zoom jetzt aktiv)",
  "v0.9038: Zoom-Button FIX — Hauptkarte: Zoom (MapControls topright) + Layer-Button (darunter) beide sichtbar (unverändert)",
  "v0.9038: Zoom-Button FIX — Mobil-Karten (Live/Route/MobilMap) haben Standard-Leaflet-Zoom (topleft, unverändert)",
  "v0.9037: Layer-Button FIX — Button positioniert UNTER den Zoom-Controls (gleiche vertikale Kontrollleiste am rechten Rand)",
  "v0.9037: Layer-Button FIX — Bei SwissTopo mit Scale-Controls wird der Button unter Zoom+Scale platziert ( dynamische Position)",
  "v0.9037: Layer-Button FIX — Min. 40x40px Touch-Target für mobile Bedienung, immer sichtbar bei allen Auflösungen",
  "v0.9037: Layer-Button FIX — Button wird nicht mehr vom Header verdeckt (vorher: top-16 = 64px, jetzt: unter Zoom-Controls)",
  "v0.9036: SOTA Cluster ENTFERNT — Backend-Runtime unterstützt keine raw TCP-Verbindungen, Cluster-Funktion konnte nie Spots liefern",
  "v0.9036: SOTA Cluster ENTFERNT — SOTAwatch-API (HTTPS) ist jetzt die EINZIGE Quelle für SOTA-Spots (identische Daten, Cluster war nur ein Spiegel)",
  "v0.9036: SOTA Cluster ENTFERNT — 12s Timeout-Delay beim Spot-Abruf komplett weg (vorher wartete jeder Abruf auf den toten Cluster)",
  "v0.9036: Cache-Zeitstempel — 'Aktualisiert: hh:mm' im Hunting-Footer zeigt letzte erfolgreige API-Aktualisierung",
  "v0.9036: Cache-Verhalten — bei API-Ausfall bleibt die letzte Spot-Liste sichtbar (kein weisser Screen, kein Leer-Anzeige)",
  "v0.9035: SOTA Cluster Login-Sequenz — sendet 'HB9OM\\n' nach login-Prompt (vorher fehlte die Anmeldung, Server schickte keine Spots)",
  "v0.9035: SOTA Cluster Frequenz-Parsing — kHz→MHz Umrechnung korrigiert (144200.0 kHz → 144.200 MHz, vorher wurden Rohwerte übergeben)",
  "v0.9035: SOTA Cluster — node:net TCP-Verbindung statt WebSocket (Server ist raw TCP, kein WS-Upgrade)",
  "v0.9035: SOTA Cluster — 12s Timeout für Login + Spot-Push, stiller Fallback bei 0 Spots (SOTAwatch-API weiter aktiv)",
  "v0.9034: Admin-Regression-Fix — Datenquellenstatus-Duplikat entfernt (war 2x vorhanden, jetzt nur noch 1x in Daten-Cache & Aktualisierung)",
  "v0.9034: Admin-Regression-Fix — PDF-Liste mit 28 Datenquellen-Referenzen wiederhergestellt (in Daten-Cache & Aktualisierung, mit PDF-Export)",
  "v0.9034: SOTA Cluster Integration — fetchSotaClusterSpots Backend-Funktion (cluster.sota.org.uk:7300, raw TCP via WebSocket-Versuch)",
  "v0.9034: SOTA Cluster Integration — Stiller Fallback: falls Cluster nicht erreichbar, SOTAwatch-API-Spots weiter verwenden (Anzeige nie leer)",
  "v0.9034: Spot-Deduplikation — gleicher Activator-Call → nur der jüngste Spot (nach Zeit), Sortierung neueste zuerst",
  "v0.9034: Spot-Deduplikation — angewendet auf SOTA Live-Spots (und alle anderen Spot-Listen im Hunting-Bereich)",
  "v0.9033: Mobil Live UI — Tone direkt neben Frequenz (gleiche Grösse, kein Label), Ort neben Rufzeichen (gleiche Grösse/Farbe)",
  "v0.9033: Mobil Live UI — Alle Modulationsarten als Badges (FM/DMR/C4FM/etc.), ausgewählte hervorgehoben, min 16px Schrift",
  "v0.9033: Mobil Live UI — +/- Buttons zum Blättern durch Relais-Liste (min 56x56px), 'Relais X/Y' Anzeige, Deaktivierung an Listen-Enden",
  "v0.9033: Mobil Live UI — Grosse Schrift für Auto-Bedienung (Frequenz 28px, Rufzeichen/Ort 22px, Tone 28px, Badges 16px, Buttons 56px)",
  "v0.9032: HOTFIX Relais verschwunden — Debug-Logs aus MobilActive entfernt (liefen bei JEDEM Render, verursachten excessive Re-Renders + 429 Rate-Limit)",
  "v0.9032: HOTFIX Relais verschwunden — `setRepeaters([])` im else-Zweig entfernt, lädt jetzt Standardbereich (Bern 100km) damit Relais immer sichtbar",
  "v0.9032: HOTFIX Relais verschwunden — Globale Repeater-Anzeige (Hauptkarte) ist SEPARAT vom Mobil-Filter, wird nicht beeinflusst",
  "v0.9031: BUGFIX Relais-Abdeckung Mobil — `if (started) return;` entfernt, Repeater werden im Live-Modus auch nach Start neu geladen (>5km Bewegung)",
  "v0.9031: BUGFIX Relais-Abdeckung Mobil — Mindest-Suchradius 50km (portable 15km war zu klein), verhindert 'Kein Repeater in Reichweite'",
  "v0.9031: BUGFIX Relais-Abdeckung Mobil — Debug-Logs: GPS-Position, Repeater-Anzahl, empfohlener Repeater mit Distanz",
  "v0.9022: Route löschen — useCallback für stabile Handler-Referenz, console.log Debugging, key-Prop für Map-Remount",
  "v0.9022: PDF Export — jsPDF client-side Generierung verifiziert, Button in Import-Gruppe sichtbar",
  "v0.9021: Route löschen Button Fix — löscht zuverlässig alle Wegpunkte, Route und Repeater",
  "v0.9021: PDF Export Button in Import-Button-Gruppe (neben GPX/Google) — immer sichtbar wenn Wegpunkte vorhanden",
  "v0.9021: Gespeicherte Route löschen — Trash-Button pro gespeicherter Route in 'Meine Routen'",
  "v0.9021: Google-Import Waypoint-Verarbeitung stabilisiert — alle Waypoints werden korrekt hinzugefügt",
  "v0.9020: Route löschen Button — Alle Wegpunkte/Route/Repeater mit Bestätigungs-Dialog entfernen",
  "v0.9020: Google-Route-Import Regression-Fix — /dir/ mit Ortsnamen geht an Backend (nicht mehr @lat,lon Fallback), Number() für Backend-Koordinaten",
  "v0.9020: PDF-Export erweitert — Routen-Abschnitt-Tabelle (Start→Ziel, Distanz) + Repeater pro Abschnitt gruppiert + Header/Footer aktualisiert",
  "v0.9019: GPX-Upload Bugfix — File-Input verwendet sr-only statt display:none (klickbar auf Mobile), accept-Attribut erweitert",
  "v0.9019: Google-Route-Import Bugfix — Frontend-Parser unterstützt !3dLAT!4dLON Format (alle Waypoints), Backend nur als Fallback für Short-Links",
  "v0.9019: Google-Route-Import — Hinweismeldung bei URLs mit Ortsnamen (keine Koordinaten)",
  "v0.9019: BAKOM-Link korrigiert — Hilfe-Seite verwendet https://www.bakom.admin.ch/de/amateurfunk + USKA Bandplan Link",
  "v0.9019: Report-Button im Relais-Popup reaktiviert — neues RepeaterReport Entity + reportRepeaterError Backend-Function",
  "v0.9019: Türkische Burgen — fetchCastlesOverpass lädt 404+ Burgen aus OpenStreetMap für COTA-Layer (Türkei, Balkan, MENA)",
  "v0.9019: COTA-Layer erweitert — 15 Länder über Overpass API (TA, SX, 4L, EK, LZ, YO, YU, ZA, Z3, E7, 4O, CN, 3V, OD, JY)",
  "v0.9018: Clubstation Filter — fetchQrzClubLog verwendet immer HB9OM als club_callsign (ignoriert ADIF STATION_CALLSIGN)",
  "v0.9018: Clubstation Filter — normalizeLogClubCall Backend-Function korrigiert bestehende Einträge (HB3YNF → HB9OM)",
  "v0.9018: Clubstation Filter — Logbuch-Filter zeigt 'Persönlich (HB3YNF)' und 'Clubstation (HB9OM)' Labels",
  "v0.9018: SOTA Sync — upsertPointsByCode mit Parallel-Batches (5 concurrent) + 250s Time-Budget statt upsertPoints",
  "v0.9018: SOTA Sync — Kein Delete-Phase mehr (upsert by code) → keine Datenverluste bei Timeout",
  "v0.9018: WWFF Sync — upsertPointsByCode verarbeitet alle 65.815 Einträge (vorher nur 9.000 wegen 110s Timeout)",
  "v0.9018: Reference Data — 10 kanonische Einträge bestätigt (keine alten Duplikate mehr)",
  "v0.9017: Repeater-Coverage Cronjob — fetchRepeaters aktualisiert DailyRefreshSchedule (success/error), Timeout-Schutz",
  "v0.9017: Repeater-Coverage Cronjob — calculateRepeaterCoverage verarbeitet nur needs_recalc/no-coverage, Batch 50/Run, 250s Time-Budget",
  "v0.9017: Repeater-Coverage Cronjob — Neuer Schedule-Eintrag 'repeater_coverage' (07:00 UTC) im Orchestrator",
  "v0.9017: LLOTA Live Spots — fetchLlotaSpots aktualisiert DailyRefreshSchedule mit last_error/last_error_detail bei Fehlern",
  "v0.9017: Reference Data — getReferencesInBounds & searchReferences verwenden nur neuesten/größten Eintrag pro Typ (keine alten Duplikate)",
  "v0.9017: Reference Data — 5 alte duplikate ReferenceData-Einträge gelöscht (castle/sota/wwbota/hbff/lighthouse)",
  "v0.9017: WWFF Sync — upsertPoints mit 120s Time-Budget verhindert Platform-Timeout bei 65k Einträgen",
  "v0.9017: Clubstation Filter — Logbuch filtert explizit is_clubstation===true (Club) / !is_clubstation (Persönlich)",
  "v0.9017: fetchQrzClubLog — STATION_CALLSIGN=HB9OM Parameter verhindert Abruf von HB3YNF QSOs",
  "v0.9017: Log Daten — normalizeLogData Backend-Function: Bänder zu lowercase, club_operator_callsign Korrektur, Duplikat-Erkennung",
  "v0.9017: Dark Mode Logbuch — dunkler Hintergrund (#1a1a1a), heller Text (#e0e0e0), Tabellen-Header (#2a2a2a), blaue Akzentfarbe",
  "v0.9017: GPX Import — File-Input über Button+Ref (klickbar auf Mobile), display:none statt hidden class",
  "v0.9016: Mobil-Modul — Karte springt nicht mehr bei manueller Interaktion (Auto-Center pausiert 5s nach Drag/Zoom)",
  "v0.9016: Mobil-Modul — GPS Auto-Center verwendet panTo mit Animation statt fitBounds Sprung",
  "v0.9016: Mobil-Modul — Throttled GPS-Updates (max 1x/3s, >10m Bewegung) verhindern ständiges Nachzentrieren",
  "v0.9016: Mobil-Modul — dBm-Ampel und Signal-Balken flackern nicht mehr (stabile HTML-Struktur, Werte aktualisieren in-place)",
  "v0.9016: Mobil-Modul — ITM Loading-Spinner nur bei Repeater-Wechsel, nicht bei jedem GPS-Update",
  "v0.9016: Mobil-Modul — Kleinere Marker: Repeater 10px→6px (aktiv), 10px→6px (normal), GPS 16px→10px",
  "v0.9016: Mobil-Modul — Coverage-Polygone dezenter (fillOpacity 0.15→0.08, weight 2→1)",
  "v0.9016: Mobil-Modul — Auto-Zoom Button: blauer Indikator wenn aktiv, sofortiger Sprung bei Tap",
  "v0.9015: Datenkonsistenz — Castle-Layer: 43 Schweizer WCA-Schlösser (HB-XXXXX) mit ReferenceData gemergt",
  "v0.9015: Datenkonsistenz — TotaPoint Duplikate entfernt (Sync lief zweimal, doppelte Records pro Code)",
  "v0.9015: Datenkonsistenz — deduplicateTotaPoints Backend-Function für zukünftige Bereinigung",
  "v0.9015: Datenkonsistenz — POTA ReferenceData total_count korrigiert (war 0, jetzt 89650)",
  "v0.9015: Datenkonsistenz — Alte duplikate ReferenceData-Einträge bereits gelöscht (5 alte IDs bestätigt nicht vorhanden)",
  "v0.9014: Elevation API Robustheit — Open-Elevation Fallback API bei OpenTopoData Rate-Limit",
  "v0.9014: Elevation API — In-Memory Cache verhindert redundante API-Calls für gleiche Koordinaten",
  "v0.9014: Elevation API — Variierter Fallback (±40m Sinus) statt flacher 500m bei API-Ausfall",
  "v0.9014: Elevation API — Interpolation für fehlende Punkte aus bekannten Nachbarn",
  "v0.9014: ITM Coverage — Feinkörnige Suche (500m Schritte) am Signal-Übergang statt hartem Abbruch",
  "v0.9014: Draggable Buttons — Per-Device-Type Speicherung (mobile/tablet/desktop getrennt)",
  "v0.9014: Draggable Buttons — Viewport-Clamping bei Resize + Orientation-Change (immer sichtbar)",
  "v0.9014: Draggable Buttons — UserHuntingSettings Struktur: { mobile: {...}, tablet: {...}, desktop: {...} }",
  "v0.9013: ITM Coverage — Terrain-Obstruktion wird JETZT im LOS-Bereich geprüft (vorher: perfekter Kreis)",
  "v0.9013: computeLongleyRice — maxObstruction Check VOR LOS-Check, Diffraction Loss auch bei LOS-Obstruktion",
  "v0.9013: computeItmCoverage — step_km von 5 auf 3 reduziert (feinere Terrain-Auflösung)",
  "v0.9013: Draggable Buttons — Position wird JETZT auch in UserHuntingSettings gespeichert (Cross-Device-Sync)",
  "v0.9013: Draggable Buttons — Beim Map-Init werden Positionen aus UserHuntingSettings geladen (überschreibt localStorage)",
  "v0.9012: Longley-Rice ITM Propagation Model mit SRTM 30m Höhendaten + Clutter-Korrektur",
  "v0.9012: computeItmPropagation Backend-Function — ITM Path-Loss zwischen zwei Punkten (OpenTopoData API)",
  "v0.9012: computeItmCoverage Backend-Function — ITM Coverage-Polygon (16 Richtungen, 5km Schritte, Batch-Elevation)",
  "v0.9012: Mobil-Modul — Repeater-Empfehlung nutzt ITM statt Freiraumdämpfung",
  "v0.9012: Mobil-Modul — Signalstärke in dBm + Qualität-Badge (🟢🔵🟡🟠🔴) im Detail-Panel",
  "v0.9012: Mobil-Modul — ITM-Details: Path Loss, ITM Loss, Clutter Loss, Fresnel Clearance",
  "v0.9012: Mobil-Modul — ITM-Qualitäts-Badges in Repeater-Liste (Top 5 nächste, debounced)",
  "v0.9012: Mobil-Modul — ITM-Coverage-Polygon statt Kreis (Terrain-basiert, 16 Richtungen)",
  "v0.9012: Draggable Buttons — Position wird gespeichert (localStorage, Long-Press 500ms auf Mobile)",
  "v0.9012: Auto-Zoom Button verschiebbar — Position persistiert über Sessions hinweg",
  "v0.9012: UserHuntingSettings — neues Feld draggable_button_positions (JSON object)",
  "v0.9012: itmModel.ts Shared Module — haversine, destinationPoint, fetchElevationProfile, computeLongleyRice, computeClutterLoss",
  "v0.9011: Auto-Zoom Button vergrößert (56x56px, weiß mit blauem Border, unten-rechts 80px/16px)",
  "v0.9011: Leaflet Attribution kompakter (font 8px, max-width 140px, ganz unten-rechts)",
  "v0.9010: High-Badge Schwelle auf 1500m ü.M. erhöht (vorher 1000m)",
  "v0.9010: Stop + Coverage-Toggle Buttons vergrößert (min 44x44px Touch-Ziel, px-3/py-2)",
  "v0.9010: Auto-Zoom Button auf Karte (unten-rechts) — fitBounds(GPS + Repeater + Route), Toggle-Modus",
  "v0.9010: Offset-Normalisierung — fehlerhafte offset_mhz Werte (kHz statt MHz, 0, falsch) korrigiert in Anzeige",
  "v0.9010: Empfangsfrequenz (Input) im Detail-Panel — klein, grau, mit Pfeil unter der Sendefrequenz",
  "v0.9010: Selektierter Repeater blinkt auf Karte (rot umrandet, fillOpacity toggle alle 500ms)",
  "v0.9010: normalizeRepeaterOffsets Backend-Function — korrigiert alle fehlerhaften Offsets in der DB (Admin)",
  "v0.9009: Repeater-Liste nach unten verschoben (unter die Karte) — Layout: Panel → Karte → Liste",
  "v0.9009: Repeater aus Liste antippen → wird aktiver Repeater (Detail-Panel + Abdeckung + Marker-Highlight)",
  "v0.9009: Repeater-Liste begrenzt — 15 nächste + High-Repeater (elevation_m > 1000m) mit 🏔 Badge",
  "v0.9008: resolveGoogleMapsLink — extrahiert ALLE Waypoints (Start + Zwischenhalt + Ziel) aus Google Maps Links",
  "v0.9008: Layout getauscht — Repeater-Panel OBEN, Repeater-Liste MITTE, Karte UNTEN (~40%) im Start-Modus",
  "v0.9008: Repeater-Abdeckung zeigt Terrain-Polygon (coverage_polygon) statt nur Kreis — grün/orange nach Reichweite",
  "v0.9008: Eigene Reichweite Polygon-Extraktion repariert (GeoJSON coordinates[0] statt ganzes Objekt)",
  "v0.9007: Mobil-Tab KOMPLETT neu implementiert — Start-Modus, Equipment-Typ, Coverage-Toggles, Backend-Function",
  "v0.9007: Start-Modus: Versteckt alle Konfiguration, zeigt nur Header (Stop+Toggles) + Karte (60%) + Repeater-Panel + Liste",
  "v0.9007: Equipment-Typ (Mobil 50W / Portable 5W) statt Slider — dynamische Reichweitenberechnung pro Band",
  "v0.9007: Repeater-Abdeckung Toggle — Kreis um empfohlenen Repeater (Radius = berechnete Reichweite)",
  "v0.9007: Eigene Reichweite Toggle — Polygon von calculateUserCoverage, Auto-Update alle 60s mit Countdown",
  "v0.9007: resolveGoogleMapsLink Backend-Function — löst Short-Links (maps.app.goo.gl) serverseitig auf",
  "v0.9007: Einklappbare Modulations-Filter (Chevron) — FM, DMR, D-STAR, C4FM, etc.",
  "v0.9007: Aktiver Repeater Panel prominent — Callsign/Frequenz groß, 'außerhalb Reichweite' Warnung bei Fallback",
  "v0.9007: Wake Lock aktiv solange Mobil-Tab offen (useMobilGps Hook)",
  "v0.9006: Unteres Menüband — Button-Abstand reduziert, alle Menüpunkte passen auf einen Screen (auch Admin)",
  "v0.9006: Unteres Menüband — flex-1 gleichbreite Buttons, min. 44px Touch-Target, horizontaler Scroll als Fallback",
  "v0.9005: Mobil-Tab — Routing & Live-Repeater-Modul (neuer Menüpunkt im unteren Menüband)",
  "v0.9005: Routenplanung — OSRM-Routing, Nominatim-Ortssuche, GPX-Import, Google Maps Link-Import",
  "v0.9005: Routenplanung — Wegpunkte Drag-to-Reorder, Reichweite-Korridor, Repeater-Filter nach Modus/Band",
  "v0.9005: Routenplanung — Repeater-Liste sortiert nach Streckenabschnitt, PDF-Export zum Programmieren",
  "v0.9005: Routenplanung — Routen speichern/laden (Route-Entity, pro User)",
  "v0.9005: Live-Modus — Empfohlener Repeater prominent (Callsign/Freq/Offset/Tone groß), Distanz + Azimuth",
  "v0.9005: Live-Modus — GPS watchPosition (high accuracy), pulsierender GPS-Marker, Accuracy-Kreis",
  "v0.9005: Live-Modus — Auto-Zentrierung, Auto-Update bei Positionsänderung (>5km)",
  "v0.9005: Wake Lock aktiv solange Mobil-Tab offen, GPS-Aktualisierung im Hintergrund",
  "v0.9005: Neue Route-Entity (waypoints, mode_filter, range_km, route_mode, total_distance_km)",
  "v0.9005: Version 0.9005 — Splash, Hamburger-Menü, Hilfe, PDF: alle auf 0.9005",
  "v0.9004: Logbuch Löschen — Bestätigungs-Dialog pro Eintrag + Batch-Löschung (Select All / Delete Selected)",
  "v0.9004: Wavelog Voll-Import — Normalisierter Dedup-Key (Suffix-Stripping /P/M/PM/MM + Zeit HH:MM) + Progress-Tracking",
  "v0.9004: QRZ Club-Log — Normalisierter Dedup-Key verhindert Duplikate durch Format-Unterschiede (Zeit HH:MM:SS vs HH:MM)",
  "v0.9004: cleanupLogDuplicates — Backend-Function zum Bereinigen existierender Duplikate (Admin)",
  "v0.9003: Wavelog Import — Paging (500 QSOs/Batch) + Dedup (callsign+date+time+freq+club)",
  "v0.9003: QRZ Club Sync — Download mit is_clubstation=true, Upload nur Club-QSOs",
  "v0.9003: Club-Log Filter — Toggle 'Nur Club-Log' im Logbuch (is_clubstation: true)",
  "v0.9003: ClubLog Upload — Neue syncClubLog Function für private QSOs (clublog.org)",
  "v0.9003: Per-User API-Keys — Wavelog Keys aus UserHuntingSettings (keine hardcoded Keys)",
  "v0.9003: Club-Log für alle — getClubLog Function (Service-Role) für Club-Mitglieder",
  "v0.9003: Station-Info — callsign HB9OM (Club), private_callsign HB3YNF",
  "v0.95: Coverage-Kreis-Fix — Filterung nutzt Fallback-Position Bern wenn kein GPS verfügbar",
  "v0.95: Grenzen-Funktion — 'Alle Grenzen anzeigen/entfernen' jetzt für alle Layer-Filter (SOTA, POTA, WWFF, IOTA, WCA, WWBOTA, LLOTA, Leuchttürme)",
  "v0.95: WWBOTA-Filter — vollwertiger Filter mit Länder-Auswahl statt einfachem Such-Filter",
  "v0.95: WCA-Filter — vollwertiger Filter mit Länder-Auswahl statt einfachem Such-Filter",
  "v0.95: Karten-Symbol-Fix — Marker z-index 1000 (Symbole verschwinden nicht mehr hinter Basis-Layern)",
  "v0.95: Aktivitätszonen als Toggle — steuert Sichtbarkeit aller Aktivitäts-Layer (SOTA, POTA, WWFF, LLOTA etc.)",
  "v0.95: Coverage-Radius — Slider 0-500km im Layer-Panel, filtert Referenzen nach Entfernung mit visuellem Kreis",
  "v0.95: Karten-Default-Position — HB9OM QTH Bern [46.979, 7.458] Zoom 9 (vorher 46.8, 8.2 Zoom 8)",
  "v0.95: LLOTA-Alerts — JSON-API llota.app/api/scheduled-activations (vorher HTML-Parser)",
  "v0.9003: LLOTA — Lakes & Lagoons on the Air Integration (8.357 Seen in 54 Ländern)",
  "v0.9003: LLOTA — neue Karten-Ebene mit Wassertropfen-Markern, Aktivierungs-Status und Länder-Filter",
  "v0.9003: LLOTA — Live-Spots von llota.app + Spothole (Merge mit Koordinaten-Anreicherung)",
  "v0.9003: LLOTA — Hunting-Tab mit Live-Spot-Aktivitäten, Sortierung nach Zeit/Score",
  "v0.9003: LLOTA — QSO-Logger Integration (my_reference_type 'llota', ADIF MY_SIG/MY_SIG_INFO)",
  "v0.9003: LLOTA — Grenzradius-Kreise (200m Aktivierungszone, konfigurierbar im Popup)",
  "v0.9003: LLOTA — Referenz-Suche, getReferencesInBounds und searchReferences erweitert",
  "v0.9003: SwissTopo BLN-Grenzen für POTA-Parks in der Schweiz (offizielles Bundesinventar-Polygon)",
  "v0.9003: POTA-Filter — Alle-Grenzen-Schalter und Grenzen-Entfernen-Button",
  "v0.9003: Grenz-Polygone blockieren keine Marker-Klicks mehr (interactive: false)",
  "v0.92: SOTA-Punkte-Filter — offizielle SOTA-Punkte-Klassifizierung (1-150 P) basierend auf Gipfelhöhe",
  "v0.92: HolyCluster — zusätzliche DX-Cluster-Quelle in fetchDxSpots integriert",
  "v0.92: Live Spot Stream — kein Limit mehr (alle Spots anzeigen, nicht nur 100)",
  "v0.92: Live Spot Activity — Multi-Select für Betriebsmodi (mehrere Modi gleichzeitig filtern)",
  "v0.92: Live Spot Activity — Quellen-Filter entfernt (alle Quellen werden angezeigt)",
  "v0.92: Layer-Ladeanzeige zurücksetzen — Button in Einstellungen → Karte",
  "v0.92: +QSO-Loggen Button — nur in Karten- und Hunting-Ansicht sichtbar",
  "v0.91001: Activity Zone Overlays — Aktivitätszonen (SOTA/POTA/WCA/IOTA/TOTA) als konfigurierbare Radius-Kreise auf der Karte",
  "v0.91001: Spothole Live Spot Stream — Live-Spots alle 30s via Spothole API ( Hunting-Seite)",
  "v0.91001: Offline-Cache TTL — Cached Daten verfallen nach 10 Minuten (automatische Aktualisierung)",
  "v0.91001: Alternative APRS-Quelle via Spothole — Positionsbasierte Stationen als Ergänzung zu aprs.fi",
  "v0.91001: Help-Dokumentation auf v0.91 aktualisiert (Zoom-Aggregation, Spothole, Activity Zones)",
  "v0.91: Zoom-Aggregation — bei Weitansicht (Zoom < 6) werden Länder-Badges mit Anzahlen gezeigt statt 10'000 einzelner Marker",
  "v0.91: Spothole API Integration — primäre Datenquelle für Spots und Propagation (kein API-Key nötig)",
  "v0.91: getReferencesInBounds repariert — entityType Parameter wird jetzt respektiert (AprsStation liefert APRS-Daten, nicht SOTA)",
  "v0.91: Deduplizierung nach Record-ID/Callsign (vorher: derselbe Punkt dutzende Male)",
  "v0.91: Layer-Lading vom Zentrum nach aussen — Punkte werden nach Entfernung zum Kartenmitte sortiert",
  "v0.91: Sauberes Layer-Toggle — AbortController bricht laufende Requests ab, Marker werden beim Ausschalten entfernt",
  "v0.91: fetchSpotholeSpots Backend-Function — lädt xOTA-Spots, DX-Cluster-Spots und Solar/Propagation-Daten",
  "Fix v0.9029: POTA-Datenverlust behoben — upsertPoints erstellt neue Datensätze ERST, dann löscht alte (vorher: löschen dann erstellen → Timeout = alle Daten weg)",
  "Fix v0.9029: Parallele bulkCreate (5 gleichzeitige Batches) beschleunigt 90K Records von >60s auf ~15s",
  "Fix v0.9029: ReferenceData total_count zeigt jetzt tatsächliche created-Anzahl (nicht points.length)",
  "Fix v0.9028: POTA worldwide — fetchPOTA verwendet immer vollständige POTA_ENTITIES Liste (API-Entity-Liste unzuverlässig, lieferte nur GB/CH/IE)",
  "Fix v0.9028: POTA/WWFF/SOTA — Deduplikation nach Code vor Cap, Sortierung nach Ländercode für geografische Diversität",
  "Fix v0.9028: POTA/WWFF — Per-Type Timeout 10s→25s, MAX_PAGES 4→20 (100k Records), MAX_PER_TYPE 10k→20k",
  "Fix v0.9028: Layer-Ausschaltung — Referenz-Typen (SOTA/POTA/WWFF/etc) werden beim Deaktivieren des Layers von der Karte gelöscht",
  "Fix v0.9028: WWFF — Italien/Schweden/Dänemark/Finnland/Norwegen jetzt sichtbar (Sortierung nach Ländercode vor Cap)",
  "Fix v0.9028: Karten-Verschiebung — Layer werden bei moveend/zoomend nachgeladen (ViewportDataLoader mit 25s Timeout)",
  "Build v0.9027: PUNKT 2 — SOTA weltweit ladbar: loadPointsInBounds ohne Sortierung + Fallback bei Timeout",
  "Build v0.9027: PUNKT 4 — POTA weltweit ladbar: ViewportDataLoader Bounds-Caching entfernt, Timeout 30s",
  "Build v0.9027: PUNKT 9 — TOTA weltweit ladbar: Sortierung entfernt, CH-Filter auf Standard true",
  "Build v0.9027: PUNKT 10 — WLOTA: Alle Leuchttürme sichtbar (ILLW ab Zoom 5, Non-ILLW ab Zoom 8)",
  "Build v0.9027: PUNKT 11 — APRS: PrivateNode MAX 5000, AprsStation als eigene Quelle in getReferencesInBounds",
  "Build v0.9027: Live Spot Activity — 60s Refresh, alle Spots (kein 50er Limit mehr)",
  "Build v0.9026: PUNKT 12 — Vollwertige Filter für SOTA (Höhe+Punkte+Land), POTA (Land), WWFF (Land), IOTA (Status+Region+Land) — alle verschiebbar",
  "Build v0.9026: PUNKT 5 — Leuchtturm-Quellen von 13 regionalen auf 1 globale ILLW-Quelle konsolidiert",
  "Build v0.9026: PUNKT 10 — DailyRefreshSchedule bereinigt: stale repeater entfernt, hbff+repeater_na_us deaktiviert, 15 regionale Leuchttürme gelöscht, WWBOTA deaktiviert",
  "Build v0.9026: PUNKT 11 — Alle Filter-Popups verwenden useDraggablePosition (long-press verschiebbar)",
  "Build v0.9025: refreshHuntingData NEU GESCHRIEBEN — Fetch-Logic INLINE (keine 403 Fehler mehr)",
  "Build v0.9025: Shared huntingFetchers.ts Modul — DX/Propagation/SOTA/POTA/WWFF/GMA Fetch-Logic zentral",
  "Build v0.9025: fetchPOTA — SDK aktualisiert + isInternalCall Support + PotaPoint Schreibung bestätigt",
  "Build v0.9025: SOTA Sync — CSV Download Timeout auf 300s erhöht (vorher Timeout nach 3 Versuchen)",
  "Build v0.9025: DX Spots — Reference-Lookup für Spots ohne Koordinaten (SOTA/POTA/WWFF/IOTA Referenz-Entities)",
  "Build v0.9025: wavelogApi permanent_sync — Auth-Prüfung entfernt (kein 401 mehr)",
  "Fix v0.9035: Log-Schema — wavelog_sync_time zu wavelog_sync_date umbenannt (Schema + wavelogApi + wavelogSync.js)",
  "Fix v0.9035: QRZ-Credentials — aus AppSetting club_callsign_config in Environment-Secrets verschoben (QRZ_USERNAME, QRZ_PASSWORD, QRZ_API_KEY)",
  "Fix v0.9035: UserHuntingSettings — WWBOTA aus selected_activity_types Default-Array und Enum entfernt",
  "Fix v0.9035: AppSetting — WWBOTA aus source_config und weekly_report_last_counts JSON entfernt",
  "Fix v0.9035: APRS-Fetch — nur stationäre Typen laden (mobile/boat/car/bike/aircraft/walker werden übersprungen)",
  "Fix v0.9035: testCredentials + manageApiKeys — QRZ-Credentials aus Environment-Secrets (keine AppSetting mehr)",
  "Fix v0.9035: Datenbereinigung — 2 TEST3-Logeinträge, 16 restore_point AppSettings, 184 mobile PrivateNodes, 7 mobile PublicPositions gelöscht",
  "Fix v0.9035: ActivityPanel — 5 Tabs (WWBOTA entfernt, Live Spot Activity als erster Tab zwischen Propagation Overview und SOTA)",
  "Fix v0.9035: UserHuntingSettings — wavelog_last_sync Feld hinzugefügt (date-time)",
  "Fix v0.9035: DataSourceStatus — status='WARN' wenn error_message vorhanden (fetchDxSpots, fetchGmaSpots korrigiert)",
  "Fix v0.9035: changelog_email_version AppSetting auf 0.9035 aktualisiert",
  "Fix v0.9035: WWBOTA aus dailyRefreshOrchestrator SOURCES und SOURCE_GROUP_TIMES entfernt",
  "Fix v0.9035: wavelogApi permanent_sync 401 Fix bestätigt (isInternal + asServiceRole)",
  "Fix v0.9035: Alle Filter-Popups (Repeater, TOTA, APRS, Lighthouse, BrandMeister) bereits mit useDraggablePosition verschiebbar",
  "Fix v0.9034: Wavelog Upload — SECURITY: api_key/wan_url/station_id aus Body werden IGNORIERT, Konfiguration kommt AUSSCHLIESSLICH aus UserHuntingSettings",
  "Fix v0.9034: Wavelog Upload — 403 Forbidden wenn Wavelog nicht aktiviert für diesen Nutzer",
  "Fix v0.9034: Wavelog Permanent Sync — Importierte QSOs bekommen wavelog_synced=true (werden nicht re-exportiert)",
  "Fix v0.9034: Wavelog Permanent Sync — Export filtert nach created_by_id + wavelog_imported=false (Per-User Isolation)",
  "Fix v0.9033: Wavelog Upload — akzeptiert mehrere Feldnamen (string, adifString, adif_data, adif, adif_string)",
  "Fix v0.9033: Wavelog Upload — bessere Response mit success, adif_count, adif_errors, message",
  "Fix v0.9033: Wavelog Permanent Sync — neue Action 'permanent_sync' (Import + Export für alle auto_sync User)",
  "Fix v0.9033: Wavelog Permanent Sync — Scheduled Automation alle 15 Minuten ruft permanent_sync auf",
  "Fix v0.9033: Wavelog Permanent Sync — verwendet asServiceRole für Multi-User-Zugriff",
  "Fix v0.9032: Wavelog Import — ADIF-Parsing und Entity-Erstellung ins Backend verlagert (wavelogApi Function)",
  "Fix v0.9032: Wavelog Import — bulkCreate in 100er-Batches, kein Dedup (alle QSOs werden importiert)",
  "Fix v0.9032: Wavelog Import — lastfetchedid wird im Backend direkt in UserHuntingSettings aktualisiert",
  "Fix v0.9032: Wavelog Import — Frontend ruft nur noch Backend auf und zeigt Resultat an",
  "Fix v0.9031: Wavelog Import — ADIF-Parser split case-insensitiv (<EOR> vs <eor>), Header-Entfernung, Batch-Import (100 QSOs pro Batch)",
  "Fix v0.9031: Wavelog Import — Dedup-Prüfung mit Frequency (callsign + qso_date + time_start + frequency)",
  "Fix v0.9031: Wavelog Import — bulkCreate statt einzelne create-Calls (2130 QSOs in 21 Batches statt 2130 Einzelaufrufen)",
  "Fix v0.9030: Live Spot Activity als eigenständiges Widget wiederhergestellt — zwischen Propagation Overview und SOTA Live-Spots",
  "Fix v0.9030: Auto-Refresh 30s, max 50 Spots angezeigt, Sortierung nach Zeit/Score/Distanz",
  "Fix v0.9029: DX-Cluster Spots im 'Live Spot Activity' Tab — Fallback auf DxSpot Entity wenn fetchDxSpots keine Spots zurückgibt",
  "Fix v0.9029: Layer-Panel OVERLAY-EBENEN — alle Layer sichtbar (Feature-Flag-Filter entfernt, Eye-Toggle steuert Karten-Sichtbarkeit)",
  "Rollback v0.9028: Zurück auf publizierten Stand — parallele fetch-Calls entfernt, refreshHuntingData Orchestrator wiederhergestellt",
  "Rollback v0.9028: Originales useEffect — nur loadData (DB) beim Mount, kein refreshFromApis im Hintergrund",
  "Rollback v0.9028: WWBOTA-Tab wiederhergestellt (6-Tabs-Struktur wie publiziert)",
  "Rollback v0.9028: DataSourceStatusSection nutzt wieder refreshHuntingData (keine parallelen Sub-Function-Calls)",
  "Fix v0.9034: Hunting-Seite hängt nicht mehr — loadData (schnell, DB) getrennt von refreshFromApis (langsam, API-Calls)",
  "Fix v0.9034: Mount + Auto-Refresh lesen nur aus DB (sofort sichtbar) — Refresh-Button triggert API-Calls",
  "Fix v0.9034: Kein Endlos-Loop, keine weisse Seite — Layer-Panel rendert sofort",
  "Fix v0.9033: refreshHuntingData Orchestrator umgangen — Frontend ruft Sub-Functions direkt per base44.functions.invoke() auf (kein 403 mehr)",
  "Fix v0.9033: ActivityPanel + DataSourceStatusSection rufen fetchSotaSpots/fetchPotaSpots/fetchWwffSpots/fetchDxSpots/fetchPropagation parallel auf",
  "Fix v0.9033: SOTA-Alerts via fetchSotaSpots({ alerts: true }) — keine separate Function nötig",
  "Fix v0.9033: Auto-Refresh (60s) ruft ebenfalls die einzelnen Functions auf, nicht mehr refreshHuntingData",
  "Fix v0.9032: refreshHuntingData nutzt base44.functions.invoke() (wie runDailySyncBatch) — kein 403 mehr",
  "Fix v0.9032: Sub-Functions erhalten { scheduled: true, internal_secret } im Body — Auth-Check wird übersprungen",
  "Fix v0.9032: Response-Parsing korrigiert (data-Wrapper bei functions.invoke)",
  "Fix v0.9031: refreshHuntingData ruft Sub-Functions direkt auf (keine 403 Fehler mehr)",
  "Fix v0.9031: SOTA-Alerts Endpoint korrigiert (/api/alerts/100/all/all statt /api/alerts)",
  "Fix v0.9031: QRT-Stationen werden als is_active: false gespeichert (SOTA, POTA, WWFF, GMA)",
  "Fix v0.9031: WWBOTA-Tab entfernt (Domain wwbota.ch tot, keine Spots mehr)",
  "Fix v0.9031: ActivitySpot Cleanup — Records >30min werden bei jedem Refresh gelöscht",
  "SOTA-Spots: RBNHOLE-Filter entfernt — jetzt 200 Spots (NORMAL + RBNHole) statt 50",
  "SOTA-Spots: RBNHole-Spots mit SNR/WPM-Info in den Kommentaren sichtbar",
  "APK-Download: downloadApk Backend-Function mit korrektem Content-Type (application/vnd.android.package-archive)",
  "APK-Upload: uploadApk Backend-Function mit Base64-Encoding umgeht Base44 Dateityp-Beschränkung",
  "Layer-Control: touchAction:none nur noch am Button — Panel scrollt wieder auf Mobile!",
  "Layer-Control: Outside-Click prüft containerRef statt panelRef — kein Flicker mehr beim Button-Klick",
  "Layer-Control: overscroll-contain verhindert Scroll-Bubbling zur Karte",
  "Error-Boundary: Per-Page Boundaries (Karte, Hunting, Logbuch, Einstellungen, Hilfe)",
  "Error-Boundary: name-Prop für gezielte Fehleranzeige + Neu-laden-Button pro Seite",
  "Karten-Fix: Layer verschwinden nicht mehr nach Aktivierung (eachLayer redraw entfernt)",
  "Karten-Fix: invalidateSize nur noch einmal pro Layer-Wechsel — keine Tile-Neuladung mehr",
  "Layer-Control: Aussenklick schliesst das Panel (Outside-Click Handler)",
  "Layer-Control: Panel bleibt stabil beim Drag-and-Drop (touchAction: none)",
  "Setup-Wizard: Dual-Flag-Check (setup_complete + wizard_completed) — erscheint nicht mehr erneut",
  "Setup-Wizard: safeStorage Wrapper verhindert Crash bei Private Browsing",
  "Stabilität: Global Error Handler (window.error + unhandledrejection) — kein White-Screen mehr",
  "Stabilität: ErrorBoundary bereits vorhanden um alle Hauptkomponenten",
  "Performance: Viewport-basiertes Laden bereits implementiert (ViewportDataLoader)",
  "Performance: Memoization bereits aktiv (useMemo für gefilterte Marker)",
  "Wavelog Fix: URLs (LAN+WAN) werden jetzt zuverlässig gespeichert (Debounce-Akkumulation)",
  "Wavelog Fix: onBlur Auto-Save beim Verlassen der Eingabefelder",
  "Wavelog Fix: station_info Fallback auf Station ID '1' (Wavelog 3.1.0 Bug Workaround)",
  "Wavelog Fix: Manuelle Station-ID Eingabe wenn station_info nicht verfügbar",
  "Wavelog Fix: Wahlschalter versteckt QRZ-Personal-Button wenn Backend = 'wavelog'",
  "Wavelog Fix: Club-QRZ-Button bleibt sichtbar (Ausnahme bei Club-Log-Filter)",
  "Wavelog Fix: Auto-Station-ID '1' wenn Settings geladen und keine Station-ID gesetzt",
  "Wavelog Fix: QSO-Save respektiert Wahlschalter (Wavelog Auto-Sync nach QSO-Save)",
  "Wavelog-Integration: Pro-User Settings (LAN+WAN URL, API Key, Station)",
  "Wavelog: Wahlschalter QRZ.com ODER Wavelog (nicht beides gleichzeitig)",
  "Wavelog: Ausnahme Club-QRZ bei Club-Log-Filter immer möglich",
  "Wavelog: Upload Button — alle nicht gesendeten QSOs an Wavelog senden",
  "Wavelog: Import Button — Delta-Sync mit lastfetchedid von Wavelog",
  "Wavelog: Permanent Sync — QSOs sofort an Wavelog senden (Auto-Sync)",
  "Wavelog: Offline Queue — QSOs offline loggen, automatisch bei Online gesendet",
  "Wavelog: Logbuch-Sync beim Öffnen — automatischer Delta-Import",
  "Wavelog: ADIF Konvertierung (QSO → ADIF → Wavelog API)",
  "Wavelog: Backend-Proxy vermeidet Mixed-Content Blocking (HTTP Server)",
  "Wavelog: Duplikat-Check beim Import (callsign + date + time)",
  "Hunting: 6-Tabs-Struktur (SOTA, POTA, WWFF, WWBOTA, Live Spot Activity, Alerts)",
  "Hunting: Keine Spot-Limits mehr — alle SOTA/POTA/WWFF/WWBOTA/DX-Spots werden angezeigt",
  "Hunting: SOTA API mit 200 Spots (3-Segment-URL /api/spots/200/all/all)",
  "Hunting: DX-Cluster speichert alle Spots (355 statt 100) — keine Slice-Limits",
  "Hunting: Spothole SIG-Spots limit=500 (war 100)",
  "Hunting: DxSpot Entity limit=500 (war 50) — merged ohne Slice",
  "Hunting: SOTA QRT/RBNHOLE-Filter aktiv (Backend + Frontend)",
  "Hunting: Alerts-Tab kombiniert SOTA-Alerts + WWFF-Agendas (260 geplante Aktivierungen)",
  "Hunting: POTA/WWBOTA-Hinweis im Alerts-Tab (keine geplante API verfügbar)",
  "UI: Gerätespezifische QSO-Button-Position (desktop/tablet/mobile getrennt)",
  "UI: Feldbreiten pro Gerät konfigurierbar (Settings → Feldbreiten pro Gerät)",
  "UI: UserHuntingSettings.ui_settings Entity-Feld für server-side Sync",
  "Karten-Fix: Stabile Container-Keys verhindern _leaflet_pos-Fehler bei View-Wechseln",
  "Zoom-Animation deaktiviert: Keine Abstürze mehr beim Schliessen von Modalen",
  "QSO-Weltkarte: Sauberes Umschalten zwischen Globus und 2D-Karte",
  "Hunting-Modul: Live DX-Spots mit GPS-basierter Distanz- und Azimuth-Berechnung",
  "Hunting-Modul: Propagation-Dashboard mit Solar Flux, K-Index und Band-Conditions",
  "Hunting-Modul: Fox Hunting mit Peilung, Triangulation und GPS-Position",
  "Hunting-Modul: QSO direkt aus Spot loggen — Formular automatisch vorausgefüllt",
  "Hunting-Modul: QRZ-Lookup direkt aus der Spot-Tabelle per Klick auf Rufzeichen",
  "GPS-Tracking: Live-Position vom Gerät überschreibt statischen Stations-Locator",
  "Build-Optimierung: Vendor-Chunks aufgeteilt für schnelleres Laden",
];

// Data sources reference — used by Help page and menu.
export const DATA_SOURCES = [
  { name: "Spothole (Spots & Propagation)", url: "spothole.app/api/v2", count: "Live-Spots + Solar", schedule: "alle 30s (Live Stream)" },
  { name: "SOTA", url: "api2.sota.org.uk", count: "~181.658 Gipfel", schedule: "täglich 03:00 UTC" },
  { name: "POTA", url: "api.pota.app", count: "~89.650 Parks", schedule: "täglich 03:30 UTC" },
  { name: "WWFF", url: "wwff.co/wwff-data/wwff_directory.csv", count: ">1.000 Gebiete", schedule: "täglich 04:00 UTC" },
  { name: "IOTA", url: "iota-world.org", count: "1.178 Gruppen", schedule: "täglich 03:00 UTC" },
  { name: "WWBOTA", url: "api.wwbota.net", count: "Bunker weltweit", schedule: "täglich 04:30 UTC" },
  { name: "Burgen/Schlösser", url: "OSM + Wikidata", count: "weltweit", schedule: "täglich 04:30 UTC" },
  { name: "Repeater", url: "RepeaterBook + hearham.com", count: ">22.000 Relais", schedule: "täglich 05:00 UTC" },
  { name: "Leuchttürme", url: "Wikidata SPARQL + Fallback", count: "weltweit", schedule: "täglich 05:30 UTC" },
  { name: "APRS", url: "aprs.fi API (API-Key)", count: "Stationen weltweit", schedule: "täglich 06:00 UTC" },
  { name: "TOTA", url: "swiss_csv + wwtota.com", count: "Antennen/Türme", schedule: "täglich 06:30 UTC" },
  { name: "LLOTA", url: "llota.app", count: "8.357 Seen/Lagunen", schedule: "wöchentlich Mo" },
  { name: "FM-Funknetz", url: "fm-funknetz.de", count: "Talkgruppen", schedule: "täglich 06:30 UTC" },
];

// Privacy notice — short text shown in menu and help.
export const PRIVACY_NOTICE =
  "Diese App verarbeitet Standortdaten zur Kartenanzeige und speichert Cache-Daten lokal auf dem Gerät. Es werden keine personenbezogenen Daten an Server übertragen ausser den für die Daten-Synchronisation nötigen API-Abfragen.";