// Embedded worldwide IOTA (Islands on the Air) reference data.
// Curated subset of major IOTA island groups from each continent.
// Source: iota-world.org IOTA program (~1200 island groups worldwide)
// Reference format: <CONTINENT>-<NUMBER>, e.g. EU-001
// Used as fallback when external IOTA CSV sources are unavailable.

export const IOTA_EMBEDDED_DATA: any[] = [
  // === Europe ===
  { code: "EU-001", name: "Faroe Islands", lat: 62.0, lng: -7.0, country: "Faroe Islands", link: "https://www.iota-world.org/" },
  { code: "EU-005", name: "Shetland Islands", lat: 60.2, lng: -1.3, country: "Scotland", link: "https://www.iota-world.org/" },
  { code: "EU-008", name: "Orkney Islands", lat: 58.9, lng: -3.2, country: "Scotland", link: "https://www.iota-world.org/" },
  { code: "EU-010", name: "Hebrides (Outer)", lat: 57.8, lng: -7.0, country: "Scotland", link: "https://www.iota-world.org/" },
  { code: "EU-012", name: "Anglesey", lat: 53.3, lng: -4.2, country: "Wales", link: "https://www.iota-world.org/" },
  { code: "EU-013", name: "Isle of Man", lat: 54.2, lng: -4.5, country: "Isle of Man", link: "https://www.iota-world.org/" },
  { code: "EU-015", name: "Scilly Isles", lat: 49.9, lng: -6.3, country: "England", link: "https://www.iota-world.org/" },
  { code: "EU-023", name: "Isle of Wight", lat: 50.7, lng: -1.3, country: "England", link: "https://www.iota-world.org/" },
  { code: "EU-024", name: "Channel Islands", lat: 49.4, lng: -2.5, country: "Channel Islands", link: "https://www.iota-world.org/" },
  { code: "EU-029", name: "Balearic Islands", lat: 39.6, lng: 2.9, country: "Spain", link: "https://www.iota-world.org/" },
  { code: "EU-033", name: "Corsica", lat: 42.0, lng: 9.0, country: "France", link: "https://www.iota-world.org/" },
  { code: "EU-034", name: "Sardinia", lat: 40.1, lng: 9.2, country: "Italy", link: "https://www.iota-world.org/" },
  { code: "EU-039", name: "Sicily", lat: 37.6, lng: 14.0, country: "Italy", link: "https://www.iota-world.org/" },
  { code: "EU-041", name: "Malta", lat: 35.9, lng: 14.4, country: "Malta", link: "https://www.iota-world.org/" },
  { code: "EU-043", name: "Crete", lat: 35.2, lng: 25.0, country: "Greece", link: "https://www.iota-world.org/" },
  { code: "EU-044", name: "Ionian Islands", lat: 38.3, lng: 20.8, country: "Greece", link: "https://www.iota-world.org/" },
  { code: "EU-049", name: "Aegean Islands (East)", lat: 37.5, lng: 27.0, country: "Greece", link: "https://www.iota-world.org/" },
  { code: "EU-057", name: "Bornholm", lat: 55.1, lng: 15.0, country: "Denmark", link: "https://www.iota-world.org/" },
  { code: "EU-063", name: "Gotland", lat: 57.5, lng: 18.5, country: "Sweden", link: "https://www.iota-world.org/" },
  { code: "EU-067", name: "Åland Islands", lat: 60.1, lng: 20.0, country: "Finland", link: "https://www.iota-world.org/" },
  { code: "EU-072", name: "Saaremaa", lat: 58.3, lng: 22.5, country: "Estonia", link: "https://www.iota-world.org/" },
  { code: "EU-075", name: "Hiiumaa", lat: 58.9, lng: 22.6, country: "Estonia", link: "https://www.iota-world.org/" },
  { code: "EU-082", name: "Iceland", lat: 64.9, lng: -19.0, country: "Iceland", link: "https://www.iota-world.org/" },
  { code: "EU-087", name: "Jan Mayen", lat: 71.0, lng: -8.5, country: "Norway", link: "https://www.iota-world.org/" },
  { code: "EU-090", name: "Svalbard", lat: 78.2, lng: 15.6, country: "Norway", link: "https://www.iota-world.org/" },
  { code: "EU-094", name: "Bear Island", lat: 74.4, lng: 19.0, country: "Norway", link: "https://www.iota-world.org/" },
  { code: "EU-099", name: "Azores", lat: 37.7, lng: -25.7, country: "Portugal", link: "https://www.iota-world.org/" },
  { code: "EU-100", name: "Madeira", lat: 32.7, lng: -16.9, country: "Portugal", link: "https://www.iota-world.org/" },
  { code: "EU-103", name: "Canary Islands", lat: 28.1, lng: -15.4, country: "Spain", link: "https://www.iota-world.org/" },
  { code: "EU-105", name: "Gibraltar", lat: 36.1, lng: -5.3, country: "Gibraltar", link: "https://www.iota-world.org/" },
  { code: "EU-115", name: "Cyprus", lat: 35.1, lng: 33.0, country: "Cyprus", link: "https://www.iota-world.org/" },
  { code: "EU-121", name: "Frøya & Hitra", lat: 63.6, lng: 8.7, country: "Norway", link: "https://www.iota-world.org/" },
  { code: "EU-125", name: "Lofoten Islands", lat: 68.2, lng: 14.6, country: "Norway", link: "https://www.iota-world.org/" },
  // === North America ===
  { code: "NA-001", name: "Newfoundland", lat: 48.5, lng: -53.0, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-003", name: "Cape Breton Island", lat: 46.1, lng: -60.5, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-005", name: "Prince Edward Island", lat: 46.4, lng: -63.2, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-008", name: "Magdalen Islands", lat: 47.4, lng: -61.9, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-011", name: "Anticosti Island", lat: 49.4, lng: -63.0, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-014", name: "Vancouver Island", lat: 49.5, lng: -125.5, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-016", name: "Haida Gwaii", lat: 53.0, lng: -131.5, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-020", name: "Banks Island", lat: 73.0, lng: -122.0, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-022", name: "Victoria Island", lat: 71.0, lng: -110.0, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-025", name: "Baffin Island", lat: 67.0, lng: -70.0, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-027", name: "Ellesmere Island", lat: 79.0, lng: -80.0, country: "Canada", link: "https://www.iota-world.org/" },
  { code: "NA-029", name: "Nantucket", lat: 41.3, lng: -70.0, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-030", name: "Martha's Vineyard", lat: 41.4, lng: -70.6, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-031", name: "Block Island", lat: 41.2, lng: -71.6, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-033", name: "Long Island (NY)", lat: 40.8, lng: -73.0, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-037", name: "Bermuda", lat: 32.3, lng: -64.8, country: "Bermuda", link: "https://www.iota-world.org/" },
  { code: "NA-044", name: "Florida Keys", lat: 24.7, lng: -81.5, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-048", name: "Santa Catalina Island", lat: 33.4, lng: -118.4, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-051", name: "San Juan Islands", lat: 48.5, lng: -123.0, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-056", name: "Kodiak Island", lat: 57.8, lng: -152.5, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-067", name: "Hawaiian Islands", lat: 19.9, lng: -155.6, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-072", name: "Aleutian Islands (East)", lat: 52.0, lng: -176.0, country: "USA", link: "https://www.iota-world.org/" },
  { code: "NA-075", name: "Guadeloupe", lat: 16.3, lng: -61.8, country: "France", link: "https://www.iota-world.org/" },
  { code: "NA-076", name: "Martinique", lat: 14.6, lng: -61.0, country: "France", link: "https://www.iota-world.org/" },
  { code: "NA-077", name: "St. Martin & St. Barts", lat: 18.1, lng: -63.1, country: "France", link: "https://www.iota-world.org/" },
  { code: "NA-078", name: "St. Kitts & Nevis", lat: 17.3, lng: -62.7, country: "St. Kitts & Nevis", link: "https://www.iota-world.org/" },
  { code: "NA-079", name: "Antigua & Barbuda", lat: 17.0, lng: -61.8, country: "Antigua & Barbuda", link: "https://www.iota-world.org/" },
  { code: "NA-080", name: "Montserrat", lat: 16.7, lng: -62.2, country: "Montserrat", link: "https://www.iota-world.org/" },
  { code: "NA-081", name: "Dominica", lat: 15.4, lng: -61.3, country: "Dominica", link: "https://www.iota-world.org/" },
  { code: "NA-082", name: "St. Lucia", lat: 13.9, lng: -61.0, country: "St. Lucia", link: "https://www.iota-world.org/" },
  { code: "NA-083", name: "St. Vincent & Grenadines", lat: 13.2, lng: -61.2, country: "St. Vincent", link: "https://www.iota-world.org/" },
  { code: "NA-084", name: "Barbados", lat: 13.2, lng: -59.5, country: "Barbados", link: "https://www.iota-world.org/" },
  { code: "NA-085", name: "Grenada", lat: 12.1, lng: -61.7, country: "Grenada", link: "https://www.iota-world.org/" },
  { code: "NA-086", name: "Trinidad & Tobago", lat: 11.0, lng: -61.0, country: "Trinidad & Tobago", link: "https://www.iota-world.org/" },
  { code: "NA-094", name: "Cozumel", lat: 20.5, lng: -87.0, country: "Mexico", link: "https://www.iota-world.org/" },
  { code: "NA-098", name: "Cuba", lat: 22.0, lng: -79.5, country: "Cuba", link: "https://www.iota-world.org/" },
  { code: "NA-104", name: "Hispaniola", lat: 19.0, lng: -71.0, country: "Dominican Republic/Haiti", link: "https://www.iota-world.org/" },
  { code: "NA-106", name: "Jamaica", lat: 18.1, lng: -77.3, country: "Jamaica", link: "https://www.iota-world.org/" },
  { code: "NA-110", name: "Puerto Rico", lat: 18.2, lng: -66.5, country: "Puerto Rico", link: "https://www.iota-world.org/" },
  { code: "NA-112", name: "Vieques & Culebra", lat: 18.1, lng: -65.4, country: "Puerto Rico", link: "https://www.iota-world.org/" },
  { code: "NA-114", name: "Bahamas", lat: 24.7, lng: -76.8, country: "Bahamas", link: "https://www.iota-world.org/" },
  { code: "NA-118", name: "Turks & Caicos", lat: 21.7, lng: -71.6, country: "Turks & Caicos", link: "https://www.iota-world.org/" },
  { code: "NA-123", name: "Cayman Islands", lat: 19.3, lng: -81.4, country: "Cayman Islands", link: "https://www.iota-world.org/" },
  // === South America ===
  { code: "SA-001", name: "Falkland Islands", lat: -51.7, lng: -59.0, country: "Falkland Islands", link: "https://www.iota-world.org/" },
  { code: "SA-003", name: "South Georgia", lat: -54.3, lng: -36.5, country: "South Georgia", link: "https://www.iota-world.org/" },
  { code: "SA-005", name: "South Orkney Islands", lat: -60.7, lng: -45.0, country: "Antarctica", link: "https://www.iota-world.org/" },
  { code: "SA-006", name: "South Shetland Islands", lat: -62.0, lng: -58.0, country: "Antarctica", link: "https://www.iota-world.org/" },
  { code: "SA-008", name: "Tierra del Fuego", lat: -54.5, lng: -68.5, country: "Argentina/Chile", link: "https://www.iota-world.org/" },
  { code: "SA-010", name: "Juan Fernández Islands", lat: -33.6, lng: -78.8, country: "Chile", link: "https://www.iota-world.org/" },
  { code: "SA-013", name: "Galápagos Islands", lat: -0.7, lng: -90.4, country: "Ecuador", link: "https://www.iota-world.org/" },
  { code: "SA-014", name: "Fernando de Noronha", lat: -3.8, lng: -32.4, country: "Brazil", link: "https://www.iota-world.org/" },
  { code: "SA-016", name: "Trindade & Martim Vaz", lat: -20.5, lng: -29.3, country: "Brazil", link: "https://www.iota-world.org/" },
  { code: "SA-020", name: "Isla Margarita", lat: 11.0, lng: -64.0, country: "Venezuela", link: "https://www.iota-world.org/" },
  { code: "SA-023", name: "San Andrés & Providencia", lat: 13.4, lng: -81.4, country: "Colombia", link: "https://www.iota-world.org/" },
  // === Asia ===
  { code: "AS-001", name: "Andaman & Nicobar Islands", lat: 11.7, lng: 92.5, country: "India", link: "https://www.iota-world.org/" },
  { code: "AS-003", name: "Sri Lanka", lat: 7.9, lng: 80.8, country: "Sri Lanka", link: "https://www.iota-world.org/" },
  { code: "AS-005", name: "Lakshadweep", lat: 10.6, lng: 72.6, country: "India", link: "https://www.iota-world.org/" },
  { code: "AS-006", name: "Maldive Islands", lat: 3.2, lng: 73.2, country: "Maldives", link: "https://www.iota-world.org/" },
  { code: "AS-007", name: "Chagos Islands", lat: -6.0, lng: 71.5, country: "Chagos", link: "https://www.iota-world.org/" },
  { code: "AS-009", name: "Cocos (Keeling) Islands", lat: -12.0, lng: 96.9, country: "Australia", link: "https://www.iota-world.org/" },
  { code: "AS-011", name: "Christmas Island", lat: -10.5, lng: 105.7, country: "Australia", link: "https://www.iota-world.org/" },
  { code: "AS-015", name: "Phuket", lat: 7.9, lng: 98.4, country: "Thailand", link: "https://www.iota-world.org/" },
  { code: "AS-020", name: "Spratly Islands", lat: 10.0, lng: 114.0, country: "Disputed", link: "https://www.iota-world.org/" },
  { code: "AS-023", name: "Palawan", lat: 9.5, lng: 118.5, country: "Philippines", link: "https://www.iota-world.org/" },
  { code: "AS-025", name: "Luzon", lat: 16.5, lng: 121.0, country: "Philippines", link: "https://www.iota-world.org/" },
  { code: "AS-026", name: "Mindanao", lat: 8.0, lng: 125.0, country: "Philippines", link: "https://www.iota-world.org/" },
  { code: "AS-028", name: "Visayan Islands", lat: 11.0, lng: 124.0, country: "Philippines", link: "https://www.iota-world.org/" },
  { code: "AS-031", name: "Borneo (East)", lat: 1.5, lng: 115.0, country: "Malaysia/Indonesia", link: "https://www.iota-world.org/" },
  { code: "AS-033", name: "Java", lat: -7.5, lng: 110.0, country: "Indonesia", link: "https://www.iota-world.org/" },
  { code: "AS-034", name: "Sumatra", lat: -0.6, lng: 102.0, country: "Indonesia", link: "https://www.iota-world.org/" },
  { code: "AS-035", name: "Sulawesi", lat: -2.5, lng: 121.0, country: "Indonesia", link: "https://www.iota-world.org/" },
  { code: "AS-038", name: "Bali & Lombok", lat: -8.5, lng: 116.0, country: "Indonesia", link: "https://www.iota-world.org/" },
  { code: "AS-041", name: "Timor", lat: -8.8, lng: 125.7, country: "Timor-Leste/Indonesia", link: "https://www.iota-world.org/" },
  { code: "AS-043", name: "Maluku Islands", lat: -3.5, lng: 128.0, country: "Indonesia", link: "https://www.iota-world.org/" },
  { code: "AS-046", name: "Papua New Guinea (West)", lat: -5.0, lng: 141.0, country: "Indonesia", link: "https://www.iota-world.org/" },
  { code: "AS-049", name: "Papua New Guinea (East)", lat: -6.0, lng: 147.0, country: "Papua New Guinea", link: "https://www.iota-world.org/" },
  { code: "AS-051", name: "Bismarck Archipelago", lat: -4.5, lng: 150.0, country: "Papua New Guinea", link: "https://www.iota-world.org/" },
  { code: "AS-055", name: "Solomon Islands", lat: -9.0, lng: 160.0, country: "Solomon Islands", link: "https://www.iota-world.org/" },
  { code: "AS-057", name: "Vanuatu", lat: -16.4, lng: 167.0, country: "Vanuatu", link: "https://www.iota-world.org/" },
  { code: "AS-058", name: "New Caledonia", lat: -21.5, lng: 165.5, country: "New Caledonia", link: "https://www.iota-world.org/" },
  { code: "AS-059", name: "Fiji Islands", lat: -17.7, lng: 178.0, country: "Fiji", link: "https://www.iota-world.org/" },
  { code: "AS-061", name: "Tonga", lat: -21.2, lng: -175.2, country: "Tonga", link: "https://www.iota-world.org/" },
  { code: "AS-063", name: "Samoa", lat: -13.6, lng: -172.2, country: "Samoa", link: "https://www.iota-world.org/" },
  { code: "AS-065", name: "American Samoa", lat: -14.3, lng: -170.7, country: "American Samoa", link: "https://www.iota-world.org/" },
  { code: "AS-066", name: "Kiribati (Gilbert Islands)", lat: 1.4, lng: 173.0, country: "Kiribati", link: "https://www.iota-world.org/" },
  { code: "AS-068", name: "Tuvalu", lat: -7.5, lng: 178.7, country: "Tuvalu", link: "https://www.iota-world.org/" },
  { code: "AS-070", name: "Tokelau", lat: -9.2, lng: -171.8, country: "Tokelau", link: "https://www.iota-world.org/" },
  { code: "AS-072", name: "Nauru", lat: -0.5, lng: 166.9, country: "Nauru", link: "https://www.iota-world.org/" },
  { code: "AS-074", name: "Marshall Islands", lat: 7.1, lng: 171.2, country: "Marshall Islands", link: "https://www.iota-world.org/" },
  { code: "AS-076", name: "Federated States of Micronesia", lat: 7.4, lng: 150.0, country: "Micronesia", link: "https://www.iota-world.org/" },
  { code: "AS-078", name: "Palau", lat: 7.5, lng: 134.6, country: "Palau", link: "https://www.iota-world.org/" },
  { code: "AS-080", name: "Guam", lat: 13.4, lng: 144.8, country: "Guam", link: "https://www.iota-world.org/" },
  { code: "AS-081", name: "Northern Mariana Islands", lat: 15.2, lng: 145.8, country: "Northern Mariana Islands", link: "https://www.iota-world.org/" },
  { code: "AS-083", name: "Hainan Island", lat: 19.2, lng: 109.7, country: "China", link: "https://www.iota-world.org/" },
  { code: "AS-086", name: "Taiwan", lat: 23.7, lng: 121.0, country: "Taiwan", link: "https://www.iota-world.org/" },
  { code: "AS-089", name: "Ryukyu Islands", lat: 26.5, lng: 128.0, country: "Japan", link: "https://www.iota-world.org/" },
  { code: "AS-091", name: "Ogasawara Islands", lat: 27.0, lng: 142.2, country: "Japan", link: "https://www.iota-world.org/" },
  { code: "AS-093", name: "Izu Islands", lat: 34.0, lng: 139.5, country: "Japan", link: "https://www.iota-world.org/" },
  { code: "AS-095", name: "Jeju Island", lat: 33.5, lng: 126.5, country: "South Korea", link: "https://www.iota-world.org/" },
  { code: "AS-098", name: "Sakhalin", lat: 50.0, lng: 143.0, country: "Russia", link: "https://www.iota-world.org/" },
  { code: "AS-100", name: "Kuril Islands", lat: 46.0, lng: 150.0, country: "Russia", link: "https://www.iota-world.org/" },
  { code: "AS-103", name: "Wrangel Island", lat: 71.2, lng: -179.5, country: "Russia", link: "https://www.iota-world.org/" },
  { code: "AS-105", name: "New Siberian Islands", lat: 75.0, lng: 145.0, country: "Russia", link: "https://www.iota-world.org/" },
  { code: "AS-108", name: "Severnaya Zemlya", lat: 79.5, lng: 95.0, country: "Russia", link: "https://www.iota-world.org/" },
  { code: "AS-110", name: "Novaya Zemlya", lat: 73.0, lng: 55.0, country: "Russia", link: "https://www.iota-world.org/" },
  { code: "AS-116", name: "Cyprus (North)", lat: 35.4, lng: 33.6, country: "Northern Cyprus", link: "https://www.iota-world.org/" },
  { code: "AS-118", name: "Bahrain", lat: 26.1, lng: 50.5, country: "Bahrain", link: "https://www.iota-world.org/" },
  { code: "AS-120", name: "Qatar", lat: 25.3, lng: 51.2, country: "Qatar", link: "https://www.iota-world.org/" },
  { code: "AS-122", name: "Socotra", lat: 12.5, lng: 53.9, country: "Yemen", link: "https://www.iota-world.org/" },
  { code: "AS-124", name: "Masirah Island", lat: 20.4, lng: 58.9, country: "Oman", link: "https://www.iota-world.org/" },
  { code: "AS-126", name: "Hormuz Island", lat: 27.1, lng: 56.5, country: "Iran", link: "https://www.iota-world.org/" },
  // === Africa ===
  { code: "AF-001", name: "Canary Islands (AF)", lat: 28.1, lng: -15.4, country: "Spain", link: "https://www.iota-world.org/" },
  { code: "AF-003", name: "Madeira (AF)", lat: 32.7, lng: -16.9, country: "Portugal", link: "https://www.iota-world.org/" },
  { code: "AF-004", name: "Cape Verde", lat: 16.0, lng: -24.0, country: "Cape Verde", link: "https://www.iota-world.org/" },
  { code: "AF-005", name: "Bioko Island", lat: 3.5, lng: 8.7, country: "Equatorial Guinea", link: "https://www.iota-world.org/" },
  { code: "AF-006", name: "São Tomé & Príncipe", lat: 0.3, lng: 6.7, country: "São Tomé & Príncipe", link: "https://www.iota-world.org/" },
  { code: "AF-007", name: "Annobón", lat: -1.4, lng: 5.6, country: "Equatorial Guinea", link: "https://www.iota-world.org/" },
  { code: "AF-008", name: "Zanzibar", lat: -6.2, lng: 39.3, country: "Tanzania", link: "https://www.iota-world.org/" },
  { code: "AF-009", name: "Pemba Island", lat: -5.2, lng: 39.8, country: "Tanzania", link: "https://www.iota-world.org/" },
  { code: "AF-010", name: "Mafia Island", lat: -7.8, lng: 39.8, country: "Tanzania", link: "https://www.iota-world.org/" },
  { code: "AF-011", name: "Comoros", lat: -11.6, lng: 43.4, country: "Comoros", link: "https://www.iota-world.org/" },
  { code: "AF-012", name: "Mayotte", lat: -12.8, lng: 45.2, country: "Mayotte", link: "https://www.iota-world.org/" },
  { code: "AF-013", name: "Madagascar", lat: -18.8, lng: 47.0, country: "Madagascar", link: "https://www.iota-world.org/" },
  { code: "AF-014", name: "Réunion", lat: -21.1, lng: 55.5, country: "France", link: "https://www.iota-world.org/" },
  { code: "AF-015", name: "Mauritius", lat: -20.3, lng: 57.6, country: "Mauritius", link: "https://www.iota-world.org/" },
  { code: "AF-016", name: "Rodrigues Island", lat: -19.7, lng: 63.4, country: "Mauritius", link: "https://www.iota-world.org/" },
  { code: "AF-017", name: "Seychelles", lat: -4.7, lng: 55.5, country: "Seychelles", link: "https://www.iota-world.org/" },
  { code: "AF-018", name: "Amirante Islands", lat: -5.4, lng: 53.3, country: "Seychelles", link: "https://www.iota-world.org/" },
  { code: "AF-019", name: "Aldabra Islands", lat: -9.4, lng: 46.4, country: "Seychelles", link: "https://www.iota-world.org/" },
  { code: "AF-020", name: "Chagos Islands (AF)", lat: -6.0, lng: 71.5, country: "Chagos", link: "https://www.iota-world.org/" },
  { code: "AF-021", name: "Dahlak Archipelago", lat: 15.6, lng: 40.2, country: "Eritrea", link: "https://www.iota-world.org/" },
  { code: "AF-022", name: "Lamu Archipelago", lat: -2.3, lng: 40.9, country: "Kenya", link: "https://www.iota-world.org/" },
  { code: "AF-023", name: "Bazaruto Archipelago", lat: -22.5, lng: 35.5, country: "Mozambique", link: "https://www.iota-world.org/" },
  { code: "AF-024", name: "Inhaca Island", lat: -26.0, lng: 33.0, country: "Mozambique", link: "https://www.iota-world.org/" },
  { code: "AF-025", name: "Prince Edward Islands", lat: -46.9, lng: 37.7, country: "South Africa", link: "https://www.iota-world.org/" },
  { code: "AF-026", name: "Djerba", lat: 33.8, lng: 11.0, country: "Tunisia", link: "https://www.iota-world.org/" },
  { code: "AF-027", name: "Kerkennah Islands", lat: 34.7, lng: 11.2, country: "Tunisia", link: "https://www.iota-world.org/" },
  { code: "AF-028", name: "Habibas Islands", lat: 35.7, lng: -2.1, country: "Algeria", link: "https://www.iota-world.org/" },
  // === Oceania ===
  { code: "OC-001", name: "Australia (Mainland)", lat: -25.3, lng: 133.8, country: "Australia", link: "https://www.iota-world.org/" },
  { code: "OC-003", name: "Tasmania", lat: -41.5, lng: 145.5, country: "Australia", link: "https://www.iota-world.org/" },
  { code: "OC-005", name: "Kangaroo Island", lat: -35.8, lng: 137.2, country: "Australia", link: "https://www.iota-world.org/" },
  { code: "OC-007", name: "Torres Strait Islands", lat: -10.6, lng: 142.2, country: "Australia", link: "https://www.iota-world.org/" },
  { code: "OC-008", name: "Lord Howe Island", lat: -31.5, lng: 159.1, country: "Australia", link: "https://www.iota-world.org/" },
  { code: "OC-009", name: "Norfolk Island", lat: -29.0, lng: 167.9, country: "Norfolk Island", link: "https://www.iota-world.org/" },
  { code: "OC-010", name: "Macquarie Island", lat: -54.6, lng: 158.9, country: "Australia", link: "https://www.iota-world.org/" },
  { code: "OC-012", name: "New Zealand (North)", lat: -39.0, lng: 174.5, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-013", name: "New Zealand (South)", lat: -44.0, lng: 170.0, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-014", name: "Stewart Island", lat: -46.8, lng: 168.0, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-015", name: "Chatham Islands", lat: -44.0, lng: -176.5, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-016", name: "Kermadec Islands", lat: -29.3, lng: -177.9, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-017", name: "Auckland Islands", lat: -50.7, lng: 166.1, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-018", name: "Campbell Island", lat: -52.5, lng: 169.0, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-019", name: "Antipodes Islands", lat: -49.7, lng: -178.8, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-020", name: "Bounty Islands", lat: -47.7, lng: -179.0, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-021", name: "Snares Islands", lat: -48.0, lng: 166.6, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-022", name: "Three Kings Islands", lat: -34.2, lng: 172.2, country: "New Zealand", link: "https://www.iota-world.org/" },
  { code: "OC-024", name: "Fiji (OC)", lat: -17.7, lng: 178.0, country: "Fiji", link: "https://www.iota-world.org/" },
  { code: "OC-026", name: "New Caledonia (OC)", lat: -21.5, lng: 165.5, country: "New Caledonia", link: "https://www.iota-world.org/" },
  { code: "OC-027", name: "Vanuatu (OC)", lat: -16.4, lng: 167.0, country: "Vanuatu", link: "https://www.iota-world.org/" },
  { code: "OC-028", name: "Solomon Islands (OC)", lat: -9.0, lng: 160.0, country: "Solomon Islands", link: "https://www.iota-world.org/" },
  { code: "OC-029", name: "Papua New Guinea (OC)", lat: -6.0, lng: 147.0, country: "Papua New Guinea", link: "https://www.iota-world.org/" },
  { code: "OC-031", name: "Caroline Islands", lat: 7.4, lng: 150.0, country: "Micronesia", link: "https://www.iota-world.org/" },
  { code: "OC-033", name: "Marshall Islands (OC)", lat: 7.1, lng: 171.2, country: "Marshall Islands", link: "https://www.iota-world.org/" },
  { code: "OC-035", name: "Gilbert Islands (OC)", lat: 1.4, lng: 173.0, country: "Kiribati", link: "https://www.iota-world.org/" },
  { code: "OC-036", name: "Phoenix Islands", lat: -3.0, lng: -172.0, country: "Kiribati", link: "https://www.iota-world.org/" },
  { code: "OC-037", name: "Line Islands", lat: 1.0, lng: -157.0, country: "Kiribati", link: "https://www.iota-world.org/" },
  { code: "OC-038", name: "Tuvalu (OC)", lat: -7.5, lng: 178.7, country: "Tuvalu", link: "https://www.iota-world.org/" },
  { code: "OC-039", name: "Tokelau (OC)", lat: -9.2, lng: -171.8, country: "Tokelau", link: "https://www.iota-world.org/" },
  { code: "OC-040", name: "Wallis & Futuna", lat: -13.3, lng: -176.2, country: "Wallis & Futuna", link: "https://www.iota-world.org/" },
  { code: "OC-041", name: "Samoa (OC)", lat: -13.6, lng: -172.2, country: "Samoa", link: "https://www.iota-world.org/" },
  { code: "OC-042", name: "American Samoa (OC)", lat: -14.3, lng: -170.7, country: "American Samoa", link: "https://www.iota-world.org/" },
  { code: "OC-043", name: "Tonga (OC)", lat: -21.2, lng: -175.2, country: "Tonga", link: "https://www.iota-world.org/" },
  { code: "OC-044", name: "Niue", lat: -19.0, lng: -169.9, country: "Niue", link: "https://www.iota-world.org/" },
  { code: "OC-045", name: "Cook Islands", lat: -21.2, lng: -159.8, country: "Cook Islands", link: "https://www.iota-world.org/" },
  { code: "OC-046", name: "French Polynesia", lat: -17.7, lng: -141.0, country: "French Polynesia", link: "https://www.iota-world.org/" },
  { code: "OC-047", name: "Pitcairn Island", lat: -25.1, lng: -130.1, country: "Pitcairn", link: "https://www.iota-world.org/" },
  { code: "OC-048", name: "Easter Island", lat: -27.1, lng: -109.4, country: "Chile", link: "https://www.iota-world.org/" },
  { code: "OC-049", name: "Juan Fernández (OC)", lat: -33.6, lng: -78.8, country: "Chile", link: "https://www.iota-world.org/" },
  { code: "OC-050", name: "Galápagos (OC)", lat: -0.7, lng: -90.4, country: "Ecuador", link: "https://www.iota-world.org/" },
  { code: "OC-051", name: "Hawaii (OC)", lat: 19.9, lng: -155.6, country: "USA", link: "https://www.iota-world.org/" },
  { code: "OC-052", name: "Johnston Atoll", lat: 16.7, lng: -169.5, country: "USA", link: "https://www.iota-world.org/" },
  { code: "OC-053", name: "Midway Atoll", lat: 28.2, lng: -177.4, country: "USA", link: "https://www.iota-world.org/" },
  { code: "OC-054", name: "Wake Island", lat: 19.3, lng: 166.6, country: "USA", link: "https://www.iota-world.org/" },
  { code: "OC-055", name: "Guam (OC)", lat: 13.4, lng: 144.8, country: "Guam", link: "https://www.iota-world.org/" },
  { code: "OC-056", name: "Northern Marianas (OC)", lat: 15.2, lng: 145.8, country: "Northern Mariana Islands", link: "https://www.iota-world.org/" },
  { code: "OC-057", name: "Nauru (OC)", lat: -0.5, lng: 166.9, country: "Nauru", link: "https://www.iota-world.org/" },
  { code: "OC-058", name: "Banaba", lat: -0.9, lng: 169.5, country: "Kiribati", link: "https://www.iota-world.org/" },
  { code: "OC-059", name: "Rotuma", lat: -12.5, lng: 177.1, country: "Fiji", link: "https://www.iota-world.org/" },
  { code: "OC-060", name: "Minerva Reefs", lat: -23.7, lng: -178.9, country: "Fiji/Tonga", link: "https://www.iota-world.org/" },
  { code: "OC-061", name: "Palmyra Atoll", lat: 5.9, lng: -162.1, country: "USA", link: "https://www.iota-world.org/" },
  { code: "OC-062", name: "Kingman Reef", lat: 6.4, lng: -162.4, country: "USA", link: "https://www.iota-world.org/" },
  { code: "OC-063", name: "Jarvis Island", lat: -0.4, lng: -160.0, country: "USA", link: "https://www.iota-world.org/" },
  { code: "OC-064", name: "Baker Island", lat: 0.2, lng: -176.5, country: "USA", link: "https://www.iota-world.org/" },
  { code: "OC-065", name: "Howland Island", lat: 0.8, lng: -176.6, country: "USA", link: "https://www.iota-world.org/" },
  { code: "OC-066", name: "Christmas Island (OC)", lat: 1.9, lng: -157.4, country: "Kiribati", link: "https://www.iota-world.org/" },
];